// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BILATERAL_PROTO_H_
#define FLATBUFFERS_GENERATED_BILATERAL_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace proto {

struct DispatchFormPayload;
struct DispatchFormPayloadBuilder;
struct DispatchFormPayloadT;

struct FreeTextPayload;
struct FreeTextPayloadBuilder;
struct FreeTextPayloadT;

struct BilateralMessage;
struct BilateralMessageBuilder;
struct BilateralMessageT;

enum BilateralKind : int8_t {
  BilateralKind_DISPATCH_FORM = 0,
  BilateralKind_FREE_TEXT = 1,
  BilateralKind_MIN = BilateralKind_DISPATCH_FORM,
  BilateralKind_MAX = BilateralKind_FREE_TEXT
};

inline const BilateralKind (&EnumValuesBilateralKind())[2] {
  static const BilateralKind values[] = {
    BilateralKind_DISPATCH_FORM,
    BilateralKind_FREE_TEXT
  };
  return values;
}

inline const char * const *EnumNamesBilateralKind() {
  static const char * const names[3] = {
    "DISPATCH_FORM",
    "FREE_TEXT",
    nullptr
  };
  return names;
}

inline const char *EnumNameBilateralKind(BilateralKind e) {
  if (::flatbuffers::IsOutRange(e, BilateralKind_DISPATCH_FORM, BilateralKind_FREE_TEXT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBilateralKind()[index];
}

enum BilateralBody : uint8_t {
  BilateralBody_NONE = 0,
  BilateralBody_DispatchFormPayload = 1,
  BilateralBody_FreeTextPayload = 2,
  BilateralBody_MIN = BilateralBody_NONE,
  BilateralBody_MAX = BilateralBody_FreeTextPayload
};

inline const BilateralBody (&EnumValuesBilateralBody())[3] {
  static const BilateralBody values[] = {
    BilateralBody_NONE,
    BilateralBody_DispatchFormPayload,
    BilateralBody_FreeTextPayload
  };
  return values;
}

inline const char * const *EnumNamesBilateralBody() {
  static const char * const names[4] = {
    "NONE",
    "DispatchFormPayload",
    "FreeTextPayload",
    nullptr
  };
  return names;
}

inline const char *EnumNameBilateralBody(BilateralBody e) {
  if (::flatbuffers::IsOutRange(e, BilateralBody_NONE, BilateralBody_FreeTextPayload)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBilateralBody()[index];
}

template<typename T> struct BilateralBodyTraits {
  static const BilateralBody enum_value = BilateralBody_NONE;
};

template<> struct BilateralBodyTraits<proto::DispatchFormPayload> {
  static const BilateralBody enum_value = BilateralBody_DispatchFormPayload;
};

template<> struct BilateralBodyTraits<proto::FreeTextPayload> {
  static const BilateralBody enum_value = BilateralBody_FreeTextPayload;
};

template<typename T> struct BilateralBodyUnionTraits {
  static const BilateralBody enum_value = BilateralBody_NONE;
};

template<> struct BilateralBodyUnionTraits<proto::DispatchFormPayloadT> {
  static const BilateralBody enum_value = BilateralBody_DispatchFormPayload;
};

template<> struct BilateralBodyUnionTraits<proto::FreeTextPayloadT> {
  static const BilateralBody enum_value = BilateralBody_FreeTextPayload;
};

struct BilateralBodyUnion {
  BilateralBody type;
  void *value;

  BilateralBodyUnion() : type(BilateralBody_NONE), value(nullptr) {}
  BilateralBodyUnion(BilateralBodyUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(BilateralBody_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  BilateralBodyUnion(const BilateralBodyUnion &);
  BilateralBodyUnion &operator=(const BilateralBodyUnion &u)
    { BilateralBodyUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  BilateralBodyUnion &operator=(BilateralBodyUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~BilateralBodyUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = BilateralBodyUnionTraits<RT>::enum_value;
    if (type != BilateralBody_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, BilateralBody type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  proto::DispatchFormPayloadT *AsDispatchFormPayload() {
    return type == BilateralBody_DispatchFormPayload ?
      reinterpret_cast<proto::DispatchFormPayloadT *>(value) : nullptr;
  }
  const proto::DispatchFormPayloadT *AsDispatchFormPayload() const {
    return type == BilateralBody_DispatchFormPayload ?
      reinterpret_cast<const proto::DispatchFormPayloadT *>(value) : nullptr;
  }
  proto::FreeTextPayloadT *AsFreeTextPayload() {
    return type == BilateralBody_FreeTextPayload ?
      reinterpret_cast<proto::FreeTextPayloadT *>(value) : nullptr;
  }
  const proto::FreeTextPayloadT *AsFreeTextPayload() const {
    return type == BilateralBody_FreeTextPayload ?
      reinterpret_cast<const proto::FreeTextPayloadT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyBilateralBody(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, BilateralBody type);
template <bool B = false>
bool VerifyBilateralBodyVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct DispatchFormPayloadT : public ::flatbuffers::NativeTable {
  typedef DispatchFormPayload TableType;
  proto::DispatchFormType form_type = proto::DispatchFormType_S2;
  std::string train_number{};
  std::vector<std::string> km_markers{};
  std::string track_number{};
};

struct DispatchFormPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DispatchFormPayloadT NativeTableType;
  typedef DispatchFormPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FORM_TYPE = 4,
    VT_TRAIN_NUMBER = 6,
    VT_KM_MARKERS = 8,
    VT_TRACK_NUMBER = 10
  };
  proto::DispatchFormType form_type() const {
    return static_cast<proto::DispatchFormType>(GetField<int8_t>(VT_FORM_TYPE, 0));
  }
  const ::flatbuffers::String *train_number() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_NUMBER);
  }
  /// Kilometre markers of the protected section (e.g. ["102.4", "118.7"]).
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *km_markers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_KM_MARKERS);
  }
  /// Track number / line side (optional, e.g. "tor 1").
  const ::flatbuffers::String *track_number() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRACK_NUMBER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_FORM_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_TRAIN_NUMBER) &&
           verifier.VerifyString(train_number()) &&
           VerifyOffset(verifier, VT_KM_MARKERS) &&
           verifier.VerifyVector(km_markers()) &&
           verifier.VerifyVectorOfStrings(km_markers()) &&
           VerifyOffset(verifier, VT_TRACK_NUMBER) &&
           verifier.VerifyString(track_number()) &&
           verifier.EndTable();
  }
  DispatchFormPayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DispatchFormPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DispatchFormPayload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchFormPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DispatchFormPayloadBuilder {
  typedef DispatchFormPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_form_type(proto::DispatchFormType form_type) {
    fbb_.AddElement<int8_t>(DispatchFormPayload::VT_FORM_TYPE, static_cast<int8_t>(form_type), 0);
  }
  void add_train_number(::flatbuffers::Offset<::flatbuffers::String> train_number) {
    fbb_.AddOffset(DispatchFormPayload::VT_TRAIN_NUMBER, train_number);
  }
  void add_km_markers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> km_markers) {
    fbb_.AddOffset(DispatchFormPayload::VT_KM_MARKERS, km_markers);
  }
  void add_track_number(::flatbuffers::Offset<::flatbuffers::String> track_number) {
    fbb_.AddOffset(DispatchFormPayload::VT_TRACK_NUMBER, track_number);
  }
  explicit DispatchFormPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DispatchFormPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DispatchFormPayload>(end);
    fbb_.Required(o, DispatchFormPayload::VT_TRAIN_NUMBER);
    return o;
  }
};

inline ::flatbuffers::Offset<DispatchFormPayload> CreateDispatchFormPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    proto::DispatchFormType form_type = proto::DispatchFormType_S2,
    ::flatbuffers::Offset<::flatbuffers::String> train_number = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> km_markers = 0,
    ::flatbuffers::Offset<::flatbuffers::String> track_number = 0) {
  DispatchFormPayloadBuilder builder_(_fbb);
  builder_.add_track_number(track_number);
  builder_.add_km_markers(km_markers);
  builder_.add_train_number(train_number);
  builder_.add_form_type(form_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DispatchFormPayload> CreateDispatchFormPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    proto::DispatchFormType form_type = proto::DispatchFormType_S2,
    const char *train_number = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *km_markers = nullptr,
    const char *track_number = nullptr) {
  auto train_number__ = train_number ? _fbb.CreateString(train_number) : 0;
  auto km_markers__ = km_markers ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*km_markers) : 0;
  auto track_number__ = track_number ? _fbb.CreateString(track_number) : 0;
  return proto::CreateDispatchFormPayload(
      _fbb,
      form_type,
      train_number__,
      km_markers__,
      track_number__);
}

::flatbuffers::Offset<DispatchFormPayload> CreateDispatchFormPayload(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchFormPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct FreeTextPayloadT : public ::flatbuffers::NativeTable {
  typedef FreeTextPayload TableType;
  std::string body{};
};

struct FreeTextPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FreeTextPayloadT NativeTableType;
  typedef FreeTextPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4
  };
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           verifier.EndTable();
  }
  FreeTextPayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(FreeTextPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<FreeTextPayload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FreeTextPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct FreeTextPayloadBuilder {
  typedef FreeTextPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(FreeTextPayload::VT_BODY, body);
  }
  explicit FreeTextPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FreeTextPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FreeTextPayload>(end);
    fbb_.Required(o, FreeTextPayload::VT_BODY);
    return o;
  }
};

inline ::flatbuffers::Offset<FreeTextPayload> CreateFreeTextPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0) {
  FreeTextPayloadBuilder builder_(_fbb);
  builder_.add_body(body);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FreeTextPayload> CreateFreeTextPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *body = nullptr) {
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return proto::CreateFreeTextPayload(
      _fbb,
      body__);
}

::flatbuffers::Offset<FreeTextPayload> CreateFreeTextPayload(::flatbuffers::FlatBufferBuilder &_fbb, const FreeTextPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BilateralMessageT : public ::flatbuffers::NativeTable {
  typedef BilateralMessage TableType;
  std::string src_area_id{};
  std::string dst_area_id{};
  proto::TelegramDirection direction = proto::TelegramDirection_SENT;
  proto::BilateralKind kind = proto::BilateralKind_DISPATCH_FORM;
  proto::BilateralBodyUnion body{};
  std::string exchange_id{};
  proto::ExchangeStatus exchange_status = proto::ExchangeStatus_PENDING;
  uint64_t timestamp_us = 0;
  std::string sender_id{};
};

struct BilateralMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BilateralMessageT NativeTableType;
  typedef BilateralMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SRC_AREA_ID = 4,
    VT_DST_AREA_ID = 6,
    VT_DIRECTION = 8,
    VT_KIND = 10,
    VT_BODY_TYPE = 12,
    VT_BODY = 14,
    VT_EXCHANGE_ID = 16,
    VT_EXCHANGE_STATUS = 18,
    VT_TIMESTAMP_US = 20,
    VT_SENDER_ID = 22
  };
  /// Dispatch area id of the initiating side (always filled by sender).
  const ::flatbuffers::String *src_area_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SRC_AREA_ID);
  }
  /// Dispatch area id of the receiving side (always filled by sender).
  const ::flatbuffers::String *dst_area_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DST_AREA_ID);
  }
  proto::TelegramDirection direction() const {
    return static_cast<proto::TelegramDirection>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  proto::BilateralKind kind() const {
    return static_cast<proto::BilateralKind>(GetField<int8_t>(VT_KIND, 0));
  }
  proto::BilateralBody body_type() const {
    return static_cast<proto::BilateralBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const proto::DispatchFormPayload *body_as_DispatchFormPayload() const {
    return body_type() == proto::BilateralBody_DispatchFormPayload ? static_cast<const proto::DispatchFormPayload *>(body()) : nullptr;
  }
  const proto::FreeTextPayload *body_as_FreeTextPayload() const {
    return body_type() == proto::BilateralBody_FreeTextPayload ? static_cast<const proto::FreeTextPayload *>(body()) : nullptr;
  }
  const ::flatbuffers::String *exchange_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXCHANGE_ID);
  }
  proto::ExchangeStatus exchange_status() const {
    return static_cast<proto::ExchangeStatus>(GetField<int8_t>(VT_EXCHANGE_STATUS, 0));
  }
  uint64_t timestamp_us() const {
    return GetField<uint64_t>(VT_TIMESTAMP_US, 0);
  }
  const ::flatbuffers::String *sender_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SENDER_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SRC_AREA_ID) &&
           verifier.VerifyString(src_area_id()) &&
           VerifyOffsetRequired(verifier, VT_DST_AREA_ID) &&
           verifier.VerifyString(dst_area_id()) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<int8_t>(verifier, VT_KIND, 1) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           VerifyBilateralBody(verifier, body(), body_type()) &&
           VerifyOffset(verifier, VT_EXCHANGE_ID) &&
           verifier.VerifyString(exchange_id()) &&
           VerifyField<int8_t>(verifier, VT_EXCHANGE_STATUS, 1) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP_US, 8) &&
           VerifyOffset(verifier, VT_SENDER_ID) &&
           verifier.VerifyString(sender_id()) &&
           verifier.EndTable();
  }
  BilateralMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BilateralMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BilateralMessage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BilateralMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const proto::DispatchFormPayload *BilateralMessage::body_as<proto::DispatchFormPayload>() const {
  return body_as_DispatchFormPayload();
}

template<> inline const proto::FreeTextPayload *BilateralMessage::body_as<proto::FreeTextPayload>() const {
  return body_as_FreeTextPayload();
}

struct BilateralMessageBuilder {
  typedef BilateralMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_src_area_id(::flatbuffers::Offset<::flatbuffers::String> src_area_id) {
    fbb_.AddOffset(BilateralMessage::VT_SRC_AREA_ID, src_area_id);
  }
  void add_dst_area_id(::flatbuffers::Offset<::flatbuffers::String> dst_area_id) {
    fbb_.AddOffset(BilateralMessage::VT_DST_AREA_ID, dst_area_id);
  }
  void add_direction(proto::TelegramDirection direction) {
    fbb_.AddElement<int8_t>(BilateralMessage::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_kind(proto::BilateralKind kind) {
    fbb_.AddElement<int8_t>(BilateralMessage::VT_KIND, static_cast<int8_t>(kind), 0);
  }
  void add_body_type(proto::BilateralBody body_type) {
    fbb_.AddElement<uint8_t>(BilateralMessage::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(BilateralMessage::VT_BODY, body);
  }
  void add_exchange_id(::flatbuffers::Offset<::flatbuffers::String> exchange_id) {
    fbb_.AddOffset(BilateralMessage::VT_EXCHANGE_ID, exchange_id);
  }
  void add_exchange_status(proto::ExchangeStatus exchange_status) {
    fbb_.AddElement<int8_t>(BilateralMessage::VT_EXCHANGE_STATUS, static_cast<int8_t>(exchange_status), 0);
  }
  void add_timestamp_us(uint64_t timestamp_us) {
    fbb_.AddElement<uint64_t>(BilateralMessage::VT_TIMESTAMP_US, timestamp_us, 0);
  }
  void add_sender_id(::flatbuffers::Offset<::flatbuffers::String> sender_id) {
    fbb_.AddOffset(BilateralMessage::VT_SENDER_ID, sender_id);
  }
  explicit BilateralMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BilateralMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BilateralMessage>(end);
    fbb_.Required(o, BilateralMessage::VT_SRC_AREA_ID);
    fbb_.Required(o, BilateralMessage::VT_DST_AREA_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<BilateralMessage> CreateBilateralMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> src_area_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dst_area_id = 0,
    proto::TelegramDirection direction = proto::TelegramDirection_SENT,
    proto::BilateralKind kind = proto::BilateralKind_DISPATCH_FORM,
    proto::BilateralBody body_type = proto::BilateralBody_NONE,
    ::flatbuffers::Offset<void> body = 0,
    ::flatbuffers::Offset<::flatbuffers::String> exchange_id = 0,
    proto::ExchangeStatus exchange_status = proto::ExchangeStatus_PENDING,
    uint64_t timestamp_us = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sender_id = 0) {
  BilateralMessageBuilder builder_(_fbb);
  builder_.add_timestamp_us(timestamp_us);
  builder_.add_sender_id(sender_id);
  builder_.add_exchange_id(exchange_id);
  builder_.add_body(body);
  builder_.add_dst_area_id(dst_area_id);
  builder_.add_src_area_id(src_area_id);
  builder_.add_exchange_status(exchange_status);
  builder_.add_body_type(body_type);
  builder_.add_kind(kind);
  builder_.add_direction(direction);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BilateralMessage> CreateBilateralMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *src_area_id = nullptr,
    const char *dst_area_id = nullptr,
    proto::TelegramDirection direction = proto::TelegramDirection_SENT,
    proto::BilateralKind kind = proto::BilateralKind_DISPATCH_FORM,
    proto::BilateralBody body_type = proto::BilateralBody_NONE,
    ::flatbuffers::Offset<void> body = 0,
    const char *exchange_id = nullptr,
    proto::ExchangeStatus exchange_status = proto::ExchangeStatus_PENDING,
    uint64_t timestamp_us = 0,
    const char *sender_id = nullptr) {
  auto src_area_id__ = src_area_id ? _fbb.CreateString(src_area_id) : 0;
  auto dst_area_id__ = dst_area_id ? _fbb.CreateString(dst_area_id) : 0;
  auto exchange_id__ = exchange_id ? _fbb.CreateString(exchange_id) : 0;
  auto sender_id__ = sender_id ? _fbb.CreateString(sender_id) : 0;
  return proto::CreateBilateralMessage(
      _fbb,
      src_area_id__,
      dst_area_id__,
      direction,
      kind,
      body_type,
      body,
      exchange_id__,
      exchange_status,
      timestamp_us,
      sender_id__);
}

::flatbuffers::Offset<BilateralMessage> CreateBilateralMessage(::flatbuffers::FlatBufferBuilder &_fbb, const BilateralMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DispatchFormPayloadT *DispatchFormPayload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DispatchFormPayloadT>(new DispatchFormPayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DispatchFormPayload::UnPackTo(DispatchFormPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = form_type(); _o->form_type = _e; }
  { auto _e = train_number(); if (_e) _o->train_number = _e->str(); }
  { auto _e = km_markers(); if (_e) { _o->km_markers.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->km_markers[_i] = _e->Get(_i)->str(); } } else { _o->km_markers.resize(0); } }
  { auto _e = track_number(); if (_e) _o->track_number = _e->str(); }
}

inline ::flatbuffers::Offset<DispatchFormPayload> CreateDispatchFormPayload(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchFormPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DispatchFormPayload::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DispatchFormPayload> DispatchFormPayload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchFormPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DispatchFormPayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _form_type = _o->form_type;
  auto _train_number = _fbb.CreateString(_o->train_number);
  auto _km_markers = _o->km_markers.size() ? _fbb.CreateVectorOfStrings(_o->km_markers) : 0;
  auto _track_number = _o->track_number.empty() ? 0 : _fbb.CreateString(_o->track_number);
  return proto::CreateDispatchFormPayload(
      _fbb,
      _form_type,
      _train_number,
      _km_markers,
      _track_number);
}

inline FreeTextPayloadT *FreeTextPayload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<FreeTextPayloadT>(new FreeTextPayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void FreeTextPayload::UnPackTo(FreeTextPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = body(); if (_e) _o->body = _e->str(); }
}

inline ::flatbuffers::Offset<FreeTextPayload> CreateFreeTextPayload(::flatbuffers::FlatBufferBuilder &_fbb, const FreeTextPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return FreeTextPayload::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<FreeTextPayload> FreeTextPayload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const FreeTextPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const FreeTextPayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _body = _fbb.CreateString(_o->body);
  return proto::CreateFreeTextPayload(
      _fbb,
      _body);
}

inline BilateralMessageT *BilateralMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BilateralMessageT>(new BilateralMessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BilateralMessage::UnPackTo(BilateralMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = src_area_id(); if (_e) _o->src_area_id = _e->str(); }
  { auto _e = dst_area_id(); if (_e) _o->dst_area_id = _e->str(); }
  { auto _e = direction(); _o->direction = _e; }
  { auto _e = kind(); _o->kind = _e; }
  { auto _e = body_type(); _o->body.type = _e; }
  { auto _e = body(); if (_e) _o->body.value = proto::BilateralBodyUnion::UnPack(_e, body_type(), _resolver); }
  { auto _e = exchange_id(); if (_e) _o->exchange_id = _e->str(); }
  { auto _e = exchange_status(); _o->exchange_status = _e; }
  { auto _e = timestamp_us(); _o->timestamp_us = _e; }
  { auto _e = sender_id(); if (_e) _o->sender_id = _e->str(); }
}

inline ::flatbuffers::Offset<BilateralMessage> CreateBilateralMessage(::flatbuffers::FlatBufferBuilder &_fbb, const BilateralMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return BilateralMessage::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BilateralMessage> BilateralMessage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BilateralMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BilateralMessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _src_area_id = _fbb.CreateString(_o->src_area_id);
  auto _dst_area_id = _fbb.CreateString(_o->dst_area_id);
  auto _direction = _o->direction;
  auto _kind = _o->kind;
  auto _body_type = _o->body.type;
  auto _body = _o->body.Pack(_fbb);
  auto _exchange_id = _o->exchange_id.empty() ? 0 : _fbb.CreateString(_o->exchange_id);
  auto _exchange_status = _o->exchange_status;
  auto _timestamp_us = _o->timestamp_us;
  auto _sender_id = _o->sender_id.empty() ? 0 : _fbb.CreateString(_o->sender_id);
  return proto::CreateBilateralMessage(
      _fbb,
      _src_area_id,
      _dst_area_id,
      _direction,
      _kind,
      _body_type,
      _body,
      _exchange_id,
      _exchange_status,
      _timestamp_us,
      _sender_id);
}

template <bool B>
inline bool VerifyBilateralBody(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, BilateralBody type) {
  switch (type) {
    case BilateralBody_NONE: {
      return true;
    }
    case BilateralBody_DispatchFormPayload: {
      auto ptr = reinterpret_cast<const proto::DispatchFormPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case BilateralBody_FreeTextPayload: {
      auto ptr = reinterpret_cast<const proto::FreeTextPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyBilateralBodyVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyBilateralBody(
        verifier,  values->Get(i), types->GetEnum<BilateralBody>(i))) {
      return false;
    }
  }
  return true;
}

inline void *BilateralBodyUnion::UnPack(const void *obj, BilateralBody type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case BilateralBody_DispatchFormPayload: {
      auto ptr = reinterpret_cast<const proto::DispatchFormPayload *>(obj);
      return ptr->UnPack(resolver);
    }
    case BilateralBody_FreeTextPayload: {
      auto ptr = reinterpret_cast<const proto::FreeTextPayload *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> BilateralBodyUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case BilateralBody_DispatchFormPayload: {
      auto ptr = reinterpret_cast<const proto::DispatchFormPayloadT *>(value);
      return CreateDispatchFormPayload(_fbb, ptr, _rehasher).Union();
    }
    case BilateralBody_FreeTextPayload: {
      auto ptr = reinterpret_cast<const proto::FreeTextPayloadT *>(value);
      return CreateFreeTextPayload(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline BilateralBodyUnion::BilateralBodyUnion(const BilateralBodyUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case BilateralBody_DispatchFormPayload: {
      value = new proto::DispatchFormPayloadT(*reinterpret_cast<proto::DispatchFormPayloadT *>(u.value));
      break;
    }
    case BilateralBody_FreeTextPayload: {
      value = new proto::FreeTextPayloadT(*reinterpret_cast<proto::FreeTextPayloadT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void BilateralBodyUnion::Reset() {
  switch (type) {
    case BilateralBody_DispatchFormPayload: {
      auto ptr = reinterpret_cast<proto::DispatchFormPayloadT *>(value);
      delete ptr;
      break;
    }
    case BilateralBody_FreeTextPayload: {
      auto ptr = reinterpret_cast<proto::FreeTextPayloadT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = BilateralBody_NONE;
}

inline const proto::BilateralMessage *GetBilateralMessage(const void *buf) {
  return ::flatbuffers::GetRoot<proto::BilateralMessage>(buf);
}

inline const proto::BilateralMessage *GetSizePrefixedBilateralMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proto::BilateralMessage>(buf);
}

template <bool B = false>
inline bool VerifyBilateralMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<proto::BilateralMessage>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedBilateralMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<proto::BilateralMessage>(nullptr);
}

inline void FinishBilateralMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::BilateralMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBilateralMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::BilateralMessage> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::BilateralMessageT> UnPackBilateralMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::BilateralMessageT>(GetBilateralMessage(buf)->UnPack(res));
}

inline std::unique_ptr<proto::BilateralMessageT> UnPackSizePrefixedBilateralMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::BilateralMessageT>(GetSizePrefixedBilateralMessage(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_BILATERAL_PROTO_H_
