// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_CHAT_PROTO_H_
#define FLATBUFFERS_GENERATED_CHAT_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR == 12 &&
                  FLATBUFFERS_VERSION_REVISION == 19,
              "Non-compatible flatbuffers version included");

namespace proto
{

struct ChatMessage;
struct ChatMessageBuilder;
struct ChatMessageT;

enum ChatTarget : int8_t
{
    ChatTarget_BROADCAST = 0,
    ChatTarget_STATION = 1,
    ChatTarget_PLAYER = 2,
    ChatTarget_MIN = ChatTarget_BROADCAST,
    ChatTarget_MAX = ChatTarget_PLAYER
};

inline const ChatTarget (&EnumValuesChatTarget())[3]
{
    static const ChatTarget values[] = {ChatTarget_BROADCAST, ChatTarget_STATION,
                                        ChatTarget_PLAYER};
    return values;
}

inline const char *const *EnumNamesChatTarget()
{
    static const char *const names[4] = {"BROADCAST", "STATION", "PLAYER", nullptr};
    return names;
}

inline const char *EnumNameChatTarget(ChatTarget e)
{
    if (::flatbuffers::IsOutRange(e, ChatTarget_BROADCAST, ChatTarget_PLAYER))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesChatTarget()[index];
}

struct ChatMessageT : public ::flatbuffers::NativeTable
{
    typedef ChatMessage TableType;
    proto::ChatTarget target = proto::ChatTarget_BROADCAST;
    std::string target_id{};
    std::string text{};
    std::string sender_id{};
    uint64_t timestamp_us = 0;
};

struct ChatMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table
{
    typedef ChatMessageT NativeTableType;
    typedef ChatMessageBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE
    {
        VT_TARGET = 4,
        VT_TARGET_ID = 6,
        VT_TEXT = 8,
        VT_SENDER_ID = 10,
        VT_TIMESTAMP_US = 12
    };
    proto::ChatTarget target() const
    {
        return static_cast<proto::ChatTarget>(GetField<int8_t>(VT_TARGET, 0));
    }
    /// Station SID for target=STATION or client_id for target=PLAYER.
    const ::flatbuffers::String *target_id() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_TARGET_ID);
    }
    /// Raw chat body; server enforces max length.
    const ::flatbuffers::String *text() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_TEXT);
    }
    /// Filled by server on outbound delivery.
    const ::flatbuffers::String *sender_id() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_SENDER_ID);
    }
    uint64_t timestamp_us() const { return GetField<uint64_t>(VT_TIMESTAMP_US, 0); }
    template<bool B = false>
    bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const
    {
        return VerifyTableStart(verifier) && VerifyField<int8_t>(verifier, VT_TARGET, 1) &&
               VerifyOffset(verifier, VT_TARGET_ID) && verifier.VerifyString(target_id()) &&
               VerifyOffsetRequired(verifier, VT_TEXT) && verifier.VerifyString(text()) &&
               VerifyOffset(verifier, VT_SENDER_ID) && verifier.VerifyString(sender_id()) &&
               VerifyField<uint64_t>(verifier, VT_TIMESTAMP_US, 8) && verifier.EndTable();
    }
    ChatMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    void UnPackTo(ChatMessageT *_o,
                  const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    static ::flatbuffers::Offset<ChatMessage> Pack(
        ::flatbuffers::FlatBufferBuilder &_fbb, const ChatMessageT *_o,
        const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ChatMessageBuilder
{
    typedef ChatMessage Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_target(proto::ChatTarget target)
    {
        fbb_.AddElement<int8_t>(ChatMessage::VT_TARGET, static_cast<int8_t>(target), 0);
    }
    void add_target_id(::flatbuffers::Offset<::flatbuffers::String> target_id)
    {
        fbb_.AddOffset(ChatMessage::VT_TARGET_ID, target_id);
    }
    void add_text(::flatbuffers::Offset<::flatbuffers::String> text)
    {
        fbb_.AddOffset(ChatMessage::VT_TEXT, text);
    }
    void add_sender_id(::flatbuffers::Offset<::flatbuffers::String> sender_id)
    {
        fbb_.AddOffset(ChatMessage::VT_SENDER_ID, sender_id);
    }
    void add_timestamp_us(uint64_t timestamp_us)
    {
        fbb_.AddElement<uint64_t>(ChatMessage::VT_TIMESTAMP_US, timestamp_us, 0);
    }
    explicit ChatMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<ChatMessage> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<ChatMessage>(end);
        fbb_.Required(o, ChatMessage::VT_TEXT);
        return o;
    }
};

inline ::flatbuffers::Offset<ChatMessage> CreateChatMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb, proto::ChatTarget target = proto::ChatTarget_BROADCAST,
    ::flatbuffers::Offset<::flatbuffers::String> target_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> text = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sender_id = 0, uint64_t timestamp_us = 0)
{
    ChatMessageBuilder builder_(_fbb);
    builder_.add_timestamp_us(timestamp_us);
    builder_.add_sender_id(sender_id);
    builder_.add_text(text);
    builder_.add_target_id(target_id);
    builder_.add_target(target);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<ChatMessage> CreateChatMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, proto::ChatTarget target = proto::ChatTarget_BROADCAST,
    const char *target_id = nullptr, const char *text = nullptr, const char *sender_id = nullptr,
    uint64_t timestamp_us = 0)
{
    auto target_id__ = target_id ? _fbb.CreateString(target_id) : 0;
    auto text__ = text ? _fbb.CreateString(text) : 0;
    auto sender_id__ = sender_id ? _fbb.CreateString(sender_id) : 0;
    return proto::CreateChatMessage(_fbb, target, target_id__, text__, sender_id__, timestamp_us);
}

::flatbuffers::Offset<ChatMessage> CreateChatMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb, const ChatMessageT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline ChatMessageT *ChatMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const
{
    auto _o = std::unique_ptr<ChatMessageT>(new ChatMessageT());
    UnPackTo(_o.get(), _resolver);
    return _o.release();
}

inline void ChatMessage::UnPackTo(ChatMessageT *_o,
                                  const ::flatbuffers::resolver_function_t *_resolver) const
{
    (void)_o;
    (void)_resolver;
    {
        auto _e = target();
        _o->target = _e;
    }
    {
        auto _e = target_id();
        if (_e)
            _o->target_id = _e->str();
    }
    {
        auto _e = text();
        if (_e)
            _o->text = _e->str();
    }
    {
        auto _e = sender_id();
        if (_e)
            _o->sender_id = _e->str();
    }
    {
        auto _e = timestamp_us();
        _o->timestamp_us = _e;
    }
}

inline ::flatbuffers::Offset<ChatMessage> CreateChatMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb, const ChatMessageT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    return ChatMessage::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ChatMessage> ChatMessage::Pack(
    ::flatbuffers::FlatBufferBuilder &_fbb, const ChatMessageT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    (void)_rehasher;
    (void)_o;
    struct _VectorArgs
    {
        ::flatbuffers::FlatBufferBuilder *__fbb;
        const ChatMessageT *__o;
        const ::flatbuffers::rehasher_function_t *__rehasher;
    } _va = {&_fbb, _o, _rehasher};
    (void)_va;
    auto _target = _o->target;
    auto _target_id = _o->target_id.empty() ? 0 : _fbb.CreateString(_o->target_id);
    auto _text = _fbb.CreateString(_o->text);
    auto _sender_id = _o->sender_id.empty() ? 0 : _fbb.CreateString(_o->sender_id);
    auto _timestamp_us = _o->timestamp_us;
    return proto::CreateChatMessage(_fbb, _target, _target_id, _text, _sender_id, _timestamp_us);
}

inline const proto::ChatMessage *GetChatMessage(const void *buf)
{
    return ::flatbuffers::GetRoot<proto::ChatMessage>(buf);
}

inline const proto::ChatMessage *GetSizePrefixedChatMessage(const void *buf)
{
    return ::flatbuffers::GetSizePrefixedRoot<proto::ChatMessage>(buf);
}

template<bool B = false>
inline bool VerifyChatMessageBuffer(::flatbuffers::VerifierTemplate<B> &verifier)
{
    return verifier.template VerifyBuffer<proto::ChatMessage>(nullptr);
}

template<bool B = false>
inline bool VerifySizePrefixedChatMessageBuffer(::flatbuffers::VerifierTemplate<B> &verifier)
{
    return verifier.template VerifySizePrefixedBuffer<proto::ChatMessage>(nullptr);
}

inline void FinishChatMessageBuffer(::flatbuffers::FlatBufferBuilder &fbb,
                                    ::flatbuffers::Offset<proto::ChatMessage> root)
{
    fbb.Finish(root);
}

inline void FinishSizePrefixedChatMessageBuffer(::flatbuffers::FlatBufferBuilder &fbb,
                                                ::flatbuffers::Offset<proto::ChatMessage> root)
{
    fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::ChatMessageT> UnPackChatMessage(
    const void *buf, const ::flatbuffers::resolver_function_t *res = nullptr)
{
    return std::unique_ptr<proto::ChatMessageT>(GetChatMessage(buf)->UnPack(res));
}

inline std::unique_ptr<proto::ChatMessageT> UnPackSizePrefixedChatMessage(
    const void *buf, const ::flatbuffers::resolver_function_t *res = nullptr)
{
    return std::unique_ptr<proto::ChatMessageT>(GetSizePrefixedChatMessage(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_CHAT_PROTO_H_
