// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_COMMON_PROTO_H_
#define FLATBUFFERS_GENERATED_COMMON_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR == 12 &&
                  FLATBUFFERS_VERSION_REVISION == 19,
              "Non-compatible flatbuffers version included");

namespace proto
{

/// Signal aspects as displayed on EbiScreen / technical diagram.
/// Values must match engine::core::SignalAspect (engine/include/engine/core/types.hpp).
enum Aspect : int8_t
{
    Aspect_S1_STOP = 0,
    Aspect_S2_PROCEED = 1,
    Aspect_S3_PROCEED_40 = 2,
    Aspect_S4_PROCEED_40_EXPECT_STOP = 3,
    Aspect_S5_EXPECT_STOP = 4,
    Aspect_S6_PROCEED_100 = 5,
    Aspect_S7_PROCEED_100_EXPECT_STOP = 6,
    Aspect_S8_PROCEED_100_EXPECT_40 = 7,
    Aspect_S9_PROCEED_100_EXPECT_60 = 8,
    Aspect_S10_PROCEED_40 = 9,
    Aspect_S11_PROCEED_40_EXPECT_40 = 10,
    Aspect_S12_PROCEED_60 = 11,
    Aspect_S13_PROCEED_60_EXPECT_60 = 12,
    Aspect_MS1_STOP = 13,
    Aspect_MS2_SHUNTING_ALLOWED = 14,
    Aspect_MIN = Aspect_S1_STOP,
    Aspect_MAX = Aspect_MS2_SHUNTING_ALLOWED
};

inline const Aspect (&EnumValuesAspect())[15]
{
    static const Aspect values[] = {Aspect_S1_STOP,
                                    Aspect_S2_PROCEED,
                                    Aspect_S3_PROCEED_40,
                                    Aspect_S4_PROCEED_40_EXPECT_STOP,
                                    Aspect_S5_EXPECT_STOP,
                                    Aspect_S6_PROCEED_100,
                                    Aspect_S7_PROCEED_100_EXPECT_STOP,
                                    Aspect_S8_PROCEED_100_EXPECT_40,
                                    Aspect_S9_PROCEED_100_EXPECT_60,
                                    Aspect_S10_PROCEED_40,
                                    Aspect_S11_PROCEED_40_EXPECT_40,
                                    Aspect_S12_PROCEED_60,
                                    Aspect_S13_PROCEED_60_EXPECT_60,
                                    Aspect_MS1_STOP,
                                    Aspect_MS2_SHUNTING_ALLOWED};
    return values;
}

inline const char *const *EnumNamesAspect()
{
    static const char *const names[16] = {"S1_STOP",
                                          "S2_PROCEED",
                                          "S3_PROCEED_40",
                                          "S4_PROCEED_40_EXPECT_STOP",
                                          "S5_EXPECT_STOP",
                                          "S6_PROCEED_100",
                                          "S7_PROCEED_100_EXPECT_STOP",
                                          "S8_PROCEED_100_EXPECT_40",
                                          "S9_PROCEED_100_EXPECT_60",
                                          "S10_PROCEED_40",
                                          "S11_PROCEED_40_EXPECT_40",
                                          "S12_PROCEED_60",
                                          "S13_PROCEED_60_EXPECT_60",
                                          "MS1_STOP",
                                          "MS2_SHUNTING_ALLOWED",
                                          nullptr};
    return names;
}

inline const char *EnumNameAspect(Aspect e)
{
    if (::flatbuffers::IsOutRange(e, Aspect_S1_STOP, Aspect_MS2_SHUNTING_ALLOWED))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesAspect()[index];
}

/// Switch (zwrotnica) position.
/// Values must match engine::core::SwitchPosition (engine/include/engine/core/types.hpp).
enum SwitchPosition : int8_t
{
    SwitchPosition_STRAIGHT = 0,
    SwitchPosition_DIVERGENT = 1,
    SwitchPosition_MOVING = 2,
    SwitchPosition_MIN = SwitchPosition_STRAIGHT,
    SwitchPosition_MAX = SwitchPosition_MOVING
};

inline const SwitchPosition (&EnumValuesSwitchPosition())[3]
{
    static const SwitchPosition values[] = {SwitchPosition_STRAIGHT, SwitchPosition_DIVERGENT,
                                            SwitchPosition_MOVING};
    return values;
}

inline const char *const *EnumNamesSwitchPosition()
{
    static const char *const names[4] = {"STRAIGHT", "DIVERGENT", "MOVING", nullptr};
    return names;
}

inline const char *EnumNameSwitchPosition(SwitchPosition e)
{
    if (::flatbuffers::IsOutRange(e, SwitchPosition_STRAIGHT, SwitchPosition_MOVING))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesSwitchPosition()[index];
}

/// Derailer (wykolejnica) position
enum DerailerPosition : int8_t
{
    DerailerPosition_LOCKED = 0,
    DerailerPosition_UNLOCKED = 1,
    DerailerPosition_MIN = DerailerPosition_LOCKED,
    DerailerPosition_MAX = DerailerPosition_UNLOCKED
};

inline const DerailerPosition (&EnumValuesDerailerPosition())[2]
{
    static const DerailerPosition values[] = {DerailerPosition_LOCKED, DerailerPosition_UNLOCKED};
    return values;
}

inline const char *const *EnumNamesDerailerPosition()
{
    static const char *const names[3] = {"LOCKED", "UNLOCKED", nullptr};
    return names;
}

inline const char *EnumNameDerailerPosition(DerailerPosition e)
{
    if (::flatbuffers::IsOutRange(e, DerailerPosition_LOCKED, DerailerPosition_UNLOCKED))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesDerailerPosition()[index];
}

/// Block section state (blok liniowy)
enum BlockSectionState : int8_t
{
    BlockSectionState_OPEN = 0,
    BlockSectionState_CLOSED = 1,
    BlockSectionState_MIN = BlockSectionState_OPEN,
    BlockSectionState_MAX = BlockSectionState_CLOSED
};

inline const BlockSectionState (&EnumValuesBlockSectionState())[2]
{
    static const BlockSectionState values[] = {BlockSectionState_OPEN, BlockSectionState_CLOSED};
    return values;
}

inline const char *const *EnumNamesBlockSectionState()
{
    static const char *const names[3] = {"OPEN", "CLOSED", nullptr};
    return names;
}

inline const char *EnumNameBlockSectionState(BlockSectionState e)
{
    if (::flatbuffers::IsOutRange(e, BlockSectionState_OPEN, BlockSectionState_CLOSED))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesBlockSectionState()[index];
}

/// SHL-12 block direction state.
/// Values must match engine::core::BlockDirectionState (engine/include/engine/core/types.hpp).
enum BlockDirectionState : int8_t
{
    BlockDirectionState_NEUTRAL = 0,
    BlockDirectionState_OUTBOUND_PENDING = 1,
    BlockDirectionState_OUTBOUND = 2,
    BlockDirectionState_INBOUND_PENDING = 3,
    BlockDirectionState_INBOUND = 4,
    BlockDirectionState_EMERGENCY = 5,
    BlockDirectionState_RESET_PENDING = 6,
    BlockDirectionState_MIN = BlockDirectionState_NEUTRAL,
    BlockDirectionState_MAX = BlockDirectionState_RESET_PENDING
};

inline const BlockDirectionState (&EnumValuesBlockDirectionState())[7]
{
    static const BlockDirectionState values[] = {
        BlockDirectionState_NEUTRAL,      BlockDirectionState_OUTBOUND_PENDING,
        BlockDirectionState_OUTBOUND,     BlockDirectionState_INBOUND_PENDING,
        BlockDirectionState_INBOUND,      BlockDirectionState_EMERGENCY,
        BlockDirectionState_RESET_PENDING};
    return values;
}

inline const char *const *EnumNamesBlockDirectionState()
{
    static const char *const names[8] = {
        "NEUTRAL", "OUTBOUND_PENDING", "OUTBOUND",      "INBOUND_PENDING",
        "INBOUND", "EMERGENCY",        "RESET_PENDING", nullptr};
    return names;
}

inline const char *EnumNameBlockDirectionState(BlockDirectionState e)
{
    if (::flatbuffers::IsOutRange(e, BlockDirectionState_NEUTRAL,
                                  BlockDirectionState_RESET_PENDING))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesBlockDirectionState()[index];
}

/// Generic cause for a state change
enum ChangeCause : int8_t
{
    ChangeCause_COMMAND = 0,
    ChangeCause_AUTO = 1,
    ChangeCause_TIMEOUT = 2,
    ChangeCause_MIN = ChangeCause_COMMAND,
    ChangeCause_MAX = ChangeCause_TIMEOUT
};

inline const ChangeCause (&EnumValuesChangeCause())[3]
{
    static const ChangeCause values[] = {ChangeCause_COMMAND, ChangeCause_AUTO,
                                         ChangeCause_TIMEOUT};
    return values;
}

inline const char *const *EnumNamesChangeCause()
{
    static const char *const names[4] = {"COMMAND", "AUTO", "TIMEOUT", nullptr};
    return names;
}

inline const char *EnumNameChangeCause(ChangeCause e)
{
    if (::flatbuffers::IsOutRange(e, ChangeCause_COMMAND, ChangeCause_TIMEOUT))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesChangeCause()[index];
}

/// Session lifecycle state
enum SessionState : int8_t
{
    SessionState_STARTED = 0,
    SessionState_PAUSED = 1,
    SessionState_RESUMED = 2,
    SessionState_ENDED = 3,
    SessionState_MIN = SessionState_STARTED,
    SessionState_MAX = SessionState_ENDED
};

inline const SessionState (&EnumValuesSessionState())[4]
{
    static const SessionState values[] = {SessionState_STARTED, SessionState_PAUSED,
                                          SessionState_RESUMED, SessionState_ENDED};
    return values;
}

inline const char *const *EnumNamesSessionState()
{
    static const char *const names[5] = {"STARTED", "PAUSED", "RESUMED", "ENDED", nullptr};
    return names;
}

inline const char *EnumNameSessionState(SessionState e)
{
    if (::flatbuffers::IsOutRange(e, SessionState_STARTED, SessionState_ENDED))
        return "";
    const size_t index = static_cast<size_t>(e);
    return EnumNamesSessionState()[index];
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_COMMON_PROTO_H_
