// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMANDS_PROTO_H_
#define FLATBUFFERS_GENERATED_COMMANDS_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace proto {

struct SetSwitchPosition;
struct SetSwitchPositionBuilder;
struct SetSwitchPositionT;

struct SetSignalAspect;
struct SetSignalAspectBuilder;
struct SetSignalAspectT;

struct SetDerailerPosition;
struct SetDerailerPositionBuilder;
struct SetDerailerPositionT;

struct SetBlockSection;
struct SetBlockSectionBuilder;
struct SetBlockSectionT;

struct RequestRoute;
struct RequestRouteBuilder;
struct RequestRouteT;

struct CancelRoute;
struct CancelRouteBuilder;
struct CancelRouteT;

struct AcknowledgeAlarm;
struct AcknowledgeAlarmBuilder;
struct AcknowledgeAlarmT;

struct SetBlockDirection;
struct SetBlockDirectionBuilder;
struct SetBlockDirectionT;

struct InitAxleCounterReset;
struct InitAxleCounterResetBuilder;
struct InitAxleCounterResetT;

struct ResetAxleCounter;
struct ResetAxleCounterBuilder;
struct ResetAxleCounterT;

struct CommandAck;
struct CommandAckBuilder;
struct CommandAckT;

struct CommandNak;
struct CommandNakBuilder;
struct CommandNakT;

/// SHL-12 block-section direction control (ESTW ML8 only).
/// Values must match engine::core::Shl12Op (engine/include/engine/core/command.hpp).
enum Shl12Op : int8_t {
  Shl12Op_BLW = 0,
  Shl12Op_BLP = 1,
  Shl12Op_BLO = 2,
  Shl12Op_BLZ = 3,
  Shl12Op_BLAI = 4,
  Shl12Op_BLA = 5,
  Shl12Op_OPS = 6,
  Shl12Op_MIN = Shl12Op_BLW,
  Shl12Op_MAX = Shl12Op_OPS
};

inline const Shl12Op (&EnumValuesShl12Op())[7] {
  static const Shl12Op values[] = {
    Shl12Op_BLW,
    Shl12Op_BLP,
    Shl12Op_BLO,
    Shl12Op_BLZ,
    Shl12Op_BLAI,
    Shl12Op_BLA,
    Shl12Op_OPS
  };
  return values;
}

inline const char * const *EnumNamesShl12Op() {
  static const char * const names[8] = {
    "BLW",
    "BLP",
    "BLO",
    "BLZ",
    "BLAI",
    "BLA",
    "OPS",
    nullptr
  };
  return names;
}

inline const char *EnumNameShl12Op(Shl12Op e) {
  if (::flatbuffers::IsOutRange(e, Shl12Op_BLW, Shl12Op_OPS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesShl12Op()[index];
}

enum NakReason : int8_t {
  NakReason_UNSPECIFIED = 0,
  NakReason_NOT_FOUND = 1,
  NakReason_SAFETY_BLOCK = 2,
  NakReason_INVALID_STATE = 3,
  NakReason_ROUTE_LOCKED = 4,
  NakReason_NO_PATH = 5,
  NakReason_SWITCH_MOVING = 6,
  NakReason_UNSUPPORTED = 7,
  NakReason_UNAUTHORIZED = 8,
  NakReason_SESSION_PAUSED = 9,
  NakReason_MIN = NakReason_UNSPECIFIED,
  NakReason_MAX = NakReason_SESSION_PAUSED
};

inline const NakReason (&EnumValuesNakReason())[10] {
  static const NakReason values[] = {
    NakReason_UNSPECIFIED,
    NakReason_NOT_FOUND,
    NakReason_SAFETY_BLOCK,
    NakReason_INVALID_STATE,
    NakReason_ROUTE_LOCKED,
    NakReason_NO_PATH,
    NakReason_SWITCH_MOVING,
    NakReason_UNSUPPORTED,
    NakReason_UNAUTHORIZED,
    NakReason_SESSION_PAUSED
  };
  return values;
}

inline const char * const *EnumNamesNakReason() {
  static const char * const names[11] = {
    "UNSPECIFIED",
    "NOT_FOUND",
    "SAFETY_BLOCK",
    "INVALID_STATE",
    "ROUTE_LOCKED",
    "NO_PATH",
    "SWITCH_MOVING",
    "UNSUPPORTED",
    "UNAUTHORIZED",
    "SESSION_PAUSED",
    nullptr
  };
  return names;
}

inline const char *EnumNameNakReason(NakReason e) {
  if (::flatbuffers::IsOutRange(e, NakReason_UNSPECIFIED, NakReason_SESSION_PAUSED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNakReason()[index];
}

struct SetSwitchPositionT : public ::flatbuffers::NativeTable {
  typedef SetSwitchPosition TableType;
  std::string g_id{};
  proto::SwitchPosition position = proto::SwitchPosition_STRAIGHT;
};

/// Move a switch (zwrotnica) to the requested position.
struct SetSwitchPosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetSwitchPositionT NativeTableType;
  typedef SetSwitchPositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_POSITION = 6
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::SwitchPosition position() const {
    return static_cast<proto::SwitchPosition>(GetField<int8_t>(VT_POSITION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_POSITION, 1) &&
           verifier.EndTable();
  }
  SetSwitchPositionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetSwitchPositionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetSwitchPosition> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSwitchPositionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetSwitchPositionBuilder {
  typedef SetSwitchPosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SetSwitchPosition::VT_G_ID, g_id);
  }
  void add_position(proto::SwitchPosition position) {
    fbb_.AddElement<int8_t>(SetSwitchPosition::VT_POSITION, static_cast<int8_t>(position), 0);
  }
  explicit SetSwitchPositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetSwitchPosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetSwitchPosition>(end);
    fbb_.Required(o, SetSwitchPosition::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SetSwitchPosition> CreateSetSwitchPosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::SwitchPosition position = proto::SwitchPosition_STRAIGHT) {
  SetSwitchPositionBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_position(position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetSwitchPosition> CreateSetSwitchPositionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::SwitchPosition position = proto::SwitchPosition_STRAIGHT) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSetSwitchPosition(
      _fbb,
      g_id__,
      position);
}

::flatbuffers::Offset<SetSwitchPosition> CreateSetSwitchPosition(::flatbuffers::FlatBufferBuilder &_fbb, const SetSwitchPositionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetSignalAspectT : public ::flatbuffers::NativeTable {
  typedef SetSignalAspect TableType;
  std::string g_id{};
  proto::Aspect aspect = proto::Aspect_S1_STOP;
};

/// Override the aspect displayed on a signal (semafor).
/// Prefer RequestRoute for normal operation; use this only for manual override.
struct SetSignalAspect FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetSignalAspectT NativeTableType;
  typedef SetSignalAspectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_ASPECT = 6
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::Aspect aspect() const {
    return static_cast<proto::Aspect>(GetField<int8_t>(VT_ASPECT, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_ASPECT, 1) &&
           verifier.EndTable();
  }
  SetSignalAspectT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetSignalAspectT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetSignalAspect> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSignalAspectT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetSignalAspectBuilder {
  typedef SetSignalAspect Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SetSignalAspect::VT_G_ID, g_id);
  }
  void add_aspect(proto::Aspect aspect) {
    fbb_.AddElement<int8_t>(SetSignalAspect::VT_ASPECT, static_cast<int8_t>(aspect), 0);
  }
  explicit SetSignalAspectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetSignalAspect> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetSignalAspect>(end);
    fbb_.Required(o, SetSignalAspect::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SetSignalAspect> CreateSetSignalAspect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::Aspect aspect = proto::Aspect_S1_STOP) {
  SetSignalAspectBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_aspect(aspect);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetSignalAspect> CreateSetSignalAspectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::Aspect aspect = proto::Aspect_S1_STOP) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSetSignalAspect(
      _fbb,
      g_id__,
      aspect);
}

::flatbuffers::Offset<SetSignalAspect> CreateSetSignalAspect(::flatbuffers::FlatBufferBuilder &_fbb, const SetSignalAspectT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetDerailerPositionT : public ::flatbuffers::NativeTable {
  typedef SetDerailerPosition TableType;
  std::string g_id{};
  proto::DerailerPosition position = proto::DerailerPosition_LOCKED;
};

/// Toggle a derailer (wykolejnica).
struct SetDerailerPosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetDerailerPositionT NativeTableType;
  typedef SetDerailerPositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_POSITION = 6
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::DerailerPosition position() const {
    return static_cast<proto::DerailerPosition>(GetField<int8_t>(VT_POSITION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_POSITION, 1) &&
           verifier.EndTable();
  }
  SetDerailerPositionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetDerailerPositionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetDerailerPosition> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetDerailerPositionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetDerailerPositionBuilder {
  typedef SetDerailerPosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SetDerailerPosition::VT_G_ID, g_id);
  }
  void add_position(proto::DerailerPosition position) {
    fbb_.AddElement<int8_t>(SetDerailerPosition::VT_POSITION, static_cast<int8_t>(position), 0);
  }
  explicit SetDerailerPositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetDerailerPosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetDerailerPosition>(end);
    fbb_.Required(o, SetDerailerPosition::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SetDerailerPosition> CreateSetDerailerPosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::DerailerPosition position = proto::DerailerPosition_LOCKED) {
  SetDerailerPositionBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_position(position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetDerailerPosition> CreateSetDerailerPositionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::DerailerPosition position = proto::DerailerPosition_LOCKED) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSetDerailerPosition(
      _fbb,
      g_id__,
      position);
}

::flatbuffers::Offset<SetDerailerPosition> CreateSetDerailerPosition(::flatbuffers::FlatBufferBuilder &_fbb, const SetDerailerPositionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetBlockSectionT : public ::flatbuffers::NativeTable {
  typedef SetBlockSection TableType;
  std::string g_id{};
  proto::BlockSectionState state = proto::BlockSectionState_OPEN;
};

/// Open or close a block section (blok liniowy).
struct SetBlockSection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetBlockSectionT NativeTableType;
  typedef SetBlockSectionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_STATE = 6
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::BlockSectionState state() const {
    return static_cast<proto::BlockSectionState>(GetField<int8_t>(VT_STATE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_STATE, 1) &&
           verifier.EndTable();
  }
  SetBlockSectionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetBlockSectionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetBlockSection> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockSectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetBlockSectionBuilder {
  typedef SetBlockSection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SetBlockSection::VT_G_ID, g_id);
  }
  void add_state(proto::BlockSectionState state) {
    fbb_.AddElement<int8_t>(SetBlockSection::VT_STATE, static_cast<int8_t>(state), 0);
  }
  explicit SetBlockSectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetBlockSection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetBlockSection>(end);
    fbb_.Required(o, SetBlockSection::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SetBlockSection> CreateSetBlockSection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::BlockSectionState state = proto::BlockSectionState_OPEN) {
  SetBlockSectionBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_state(state);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetBlockSection> CreateSetBlockSectionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::BlockSectionState state = proto::BlockSectionState_OPEN) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSetBlockSection(
      _fbb,
      g_id__,
      state);
}

::flatbuffers::Offset<SetBlockSection> CreateSetBlockSection(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockSectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RequestRouteT : public ::flatbuffers::NativeTable {
  typedef RequestRoute TableType;
  std::string from_signal_g_id{};
  std::string to_signal_g_id{};
};

/// High-level route request.
/// The engine resolves required switch positions and signal aspects internally.
struct RequestRoute FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestRouteT NativeTableType;
  typedef RequestRouteBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FROM_SIGNAL_G_ID = 4,
    VT_TO_SIGNAL_G_ID = 6
  };
  const ::flatbuffers::String *from_signal_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FROM_SIGNAL_G_ID);
  }
  const ::flatbuffers::String *to_signal_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TO_SIGNAL_G_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_FROM_SIGNAL_G_ID) &&
           verifier.VerifyString(from_signal_g_id()) &&
           VerifyOffsetRequired(verifier, VT_TO_SIGNAL_G_ID) &&
           verifier.VerifyString(to_signal_g_id()) &&
           verifier.EndTable();
  }
  RequestRouteT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RequestRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RequestRoute> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RequestRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RequestRouteBuilder {
  typedef RequestRoute Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_from_signal_g_id(::flatbuffers::Offset<::flatbuffers::String> from_signal_g_id) {
    fbb_.AddOffset(RequestRoute::VT_FROM_SIGNAL_G_ID, from_signal_g_id);
  }
  void add_to_signal_g_id(::flatbuffers::Offset<::flatbuffers::String> to_signal_g_id) {
    fbb_.AddOffset(RequestRoute::VT_TO_SIGNAL_G_ID, to_signal_g_id);
  }
  explicit RequestRouteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RequestRoute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RequestRoute>(end);
    fbb_.Required(o, RequestRoute::VT_FROM_SIGNAL_G_ID);
    fbb_.Required(o, RequestRoute::VT_TO_SIGNAL_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<RequestRoute> CreateRequestRoute(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> from_signal_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> to_signal_g_id = 0) {
  RequestRouteBuilder builder_(_fbb);
  builder_.add_to_signal_g_id(to_signal_g_id);
  builder_.add_from_signal_g_id(from_signal_g_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RequestRoute> CreateRequestRouteDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *from_signal_g_id = nullptr,
    const char *to_signal_g_id = nullptr) {
  auto from_signal_g_id__ = from_signal_g_id ? _fbb.CreateString(from_signal_g_id) : 0;
  auto to_signal_g_id__ = to_signal_g_id ? _fbb.CreateString(to_signal_g_id) : 0;
  return proto::CreateRequestRoute(
      _fbb,
      from_signal_g_id__,
      to_signal_g_id__);
}

::flatbuffers::Offset<RequestRoute> CreateRequestRoute(::flatbuffers::FlatBufferBuilder &_fbb, const RequestRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CancelRouteT : public ::flatbuffers::NativeTable {
  typedef CancelRoute TableType;
  std::string route_id{};
};

/// Cancel a previously set route.
struct CancelRoute FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CancelRouteT NativeTableType;
  typedef CancelRouteBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROUTE_ID = 4
  };
  const ::flatbuffers::String *route_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROUTE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ROUTE_ID) &&
           verifier.VerifyString(route_id()) &&
           verifier.EndTable();
  }
  CancelRouteT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CancelRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CancelRoute> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CancelRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CancelRouteBuilder {
  typedef CancelRoute Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_route_id(::flatbuffers::Offset<::flatbuffers::String> route_id) {
    fbb_.AddOffset(CancelRoute::VT_ROUTE_ID, route_id);
  }
  explicit CancelRouteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CancelRoute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CancelRoute>(end);
    fbb_.Required(o, CancelRoute::VT_ROUTE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<CancelRoute> CreateCancelRoute(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> route_id = 0) {
  CancelRouteBuilder builder_(_fbb);
  builder_.add_route_id(route_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CancelRoute> CreateCancelRouteDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *route_id = nullptr) {
  auto route_id__ = route_id ? _fbb.CreateString(route_id) : 0;
  return proto::CreateCancelRoute(
      _fbb,
      route_id__);
}

::flatbuffers::Offset<CancelRoute> CreateCancelRoute(::flatbuffers::FlatBufferBuilder &_fbb, const CancelRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AcknowledgeAlarmT : public ::flatbuffers::NativeTable {
  typedef AcknowledgeAlarm TableType;
  std::string alarm_id{};
};

/// Acknowledge an alarm displayed on the dispatcher's panel.
struct AcknowledgeAlarm FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AcknowledgeAlarmT NativeTableType;
  typedef AcknowledgeAlarmBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ALARM_ID = 4
  };
  const ::flatbuffers::String *alarm_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALARM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ALARM_ID) &&
           verifier.VerifyString(alarm_id()) &&
           verifier.EndTable();
  }
  AcknowledgeAlarmT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AcknowledgeAlarmT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AcknowledgeAlarm> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AcknowledgeAlarmT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AcknowledgeAlarmBuilder {
  typedef AcknowledgeAlarm Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_alarm_id(::flatbuffers::Offset<::flatbuffers::String> alarm_id) {
    fbb_.AddOffset(AcknowledgeAlarm::VT_ALARM_ID, alarm_id);
  }
  explicit AcknowledgeAlarmBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AcknowledgeAlarm> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AcknowledgeAlarm>(end);
    fbb_.Required(o, AcknowledgeAlarm::VT_ALARM_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<AcknowledgeAlarm> CreateAcknowledgeAlarm(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> alarm_id = 0) {
  AcknowledgeAlarmBuilder builder_(_fbb);
  builder_.add_alarm_id(alarm_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AcknowledgeAlarm> CreateAcknowledgeAlarmDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *alarm_id = nullptr) {
  auto alarm_id__ = alarm_id ? _fbb.CreateString(alarm_id) : 0;
  return proto::CreateAcknowledgeAlarm(
      _fbb,
      alarm_id__);
}

::flatbuffers::Offset<AcknowledgeAlarm> CreateAcknowledgeAlarm(::flatbuffers::FlatBufferBuilder &_fbb, const AcknowledgeAlarmT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SetBlockDirectionT : public ::flatbuffers::NativeTable {
  typedef SetBlockDirection TableType;
  std::string block_section_g_id{};
  proto::Shl12Op operation = proto::Shl12Op_BLW;
};

struct SetBlockDirection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetBlockDirectionT NativeTableType;
  typedef SetBlockDirectionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_SECTION_G_ID = 4,
    VT_OPERATION = 6
  };
  const ::flatbuffers::String *block_section_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BLOCK_SECTION_G_ID);
  }
  proto::Shl12Op operation() const {
    return static_cast<proto::Shl12Op>(GetField<int8_t>(VT_OPERATION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BLOCK_SECTION_G_ID) &&
           verifier.VerifyString(block_section_g_id()) &&
           VerifyField<int8_t>(verifier, VT_OPERATION, 1) &&
           verifier.EndTable();
  }
  SetBlockDirectionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SetBlockDirectionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SetBlockDirection> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockDirectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SetBlockDirectionBuilder {
  typedef SetBlockDirection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_section_g_id(::flatbuffers::Offset<::flatbuffers::String> block_section_g_id) {
    fbb_.AddOffset(SetBlockDirection::VT_BLOCK_SECTION_G_ID, block_section_g_id);
  }
  void add_operation(proto::Shl12Op operation) {
    fbb_.AddElement<int8_t>(SetBlockDirection::VT_OPERATION, static_cast<int8_t>(operation), 0);
  }
  explicit SetBlockDirectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetBlockDirection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetBlockDirection>(end);
    fbb_.Required(o, SetBlockDirection::VT_BLOCK_SECTION_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SetBlockDirection> CreateSetBlockDirection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> block_section_g_id = 0,
    proto::Shl12Op operation = proto::Shl12Op_BLW) {
  SetBlockDirectionBuilder builder_(_fbb);
  builder_.add_block_section_g_id(block_section_g_id);
  builder_.add_operation(operation);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetBlockDirection> CreateSetBlockDirectionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *block_section_g_id = nullptr,
    proto::Shl12Op operation = proto::Shl12Op_BLW) {
  auto block_section_g_id__ = block_section_g_id ? _fbb.CreateString(block_section_g_id) : 0;
  return proto::CreateSetBlockDirection(
      _fbb,
      block_section_g_id__,
      operation);
}

::flatbuffers::Offset<SetBlockDirection> CreateSetBlockDirection(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockDirectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct InitAxleCounterResetT : public ::flatbuffers::NativeTable {
  typedef InitAxleCounterReset TableType;
  std::string block_section_g_id{};
};

/// Initiate axle-counter reset sequence (SLI — ESTW ML8 only).
struct InitAxleCounterReset FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InitAxleCounterResetT NativeTableType;
  typedef InitAxleCounterResetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_SECTION_G_ID = 4
  };
  const ::flatbuffers::String *block_section_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BLOCK_SECTION_G_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BLOCK_SECTION_G_ID) &&
           verifier.VerifyString(block_section_g_id()) &&
           verifier.EndTable();
  }
  InitAxleCounterResetT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InitAxleCounterResetT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InitAxleCounterReset> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InitAxleCounterResetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InitAxleCounterResetBuilder {
  typedef InitAxleCounterReset Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_section_g_id(::flatbuffers::Offset<::flatbuffers::String> block_section_g_id) {
    fbb_.AddOffset(InitAxleCounterReset::VT_BLOCK_SECTION_G_ID, block_section_g_id);
  }
  explicit InitAxleCounterResetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InitAxleCounterReset> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InitAxleCounterReset>(end);
    fbb_.Required(o, InitAxleCounterReset::VT_BLOCK_SECTION_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<InitAxleCounterReset> CreateInitAxleCounterReset(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> block_section_g_id = 0) {
  InitAxleCounterResetBuilder builder_(_fbb);
  builder_.add_block_section_g_id(block_section_g_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<InitAxleCounterReset> CreateInitAxleCounterResetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *block_section_g_id = nullptr) {
  auto block_section_g_id__ = block_section_g_id ? _fbb.CreateString(block_section_g_id) : 0;
  return proto::CreateInitAxleCounterReset(
      _fbb,
      block_section_g_id__);
}

::flatbuffers::Offset<InitAxleCounterReset> CreateInitAxleCounterReset(::flatbuffers::FlatBufferBuilder &_fbb, const InitAxleCounterResetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ResetAxleCounterT : public ::flatbuffers::NativeTable {
  typedef ResetAxleCounter TableType;
  std::string block_section_g_id{};
};

/// Execute axle-counter reset (SLK — ESTW ML8 only).
struct ResetAxleCounter FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResetAxleCounterT NativeTableType;
  typedef ResetAxleCounterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCK_SECTION_G_ID = 4
  };
  const ::flatbuffers::String *block_section_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BLOCK_SECTION_G_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BLOCK_SECTION_G_ID) &&
           verifier.VerifyString(block_section_g_id()) &&
           verifier.EndTable();
  }
  ResetAxleCounterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ResetAxleCounterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ResetAxleCounter> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResetAxleCounterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ResetAxleCounterBuilder {
  typedef ResetAxleCounter Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_block_section_g_id(::flatbuffers::Offset<::flatbuffers::String> block_section_g_id) {
    fbb_.AddOffset(ResetAxleCounter::VT_BLOCK_SECTION_G_ID, block_section_g_id);
  }
  explicit ResetAxleCounterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResetAxleCounter> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResetAxleCounter>(end);
    fbb_.Required(o, ResetAxleCounter::VT_BLOCK_SECTION_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<ResetAxleCounter> CreateResetAxleCounter(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> block_section_g_id = 0) {
  ResetAxleCounterBuilder builder_(_fbb);
  builder_.add_block_section_g_id(block_section_g_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ResetAxleCounter> CreateResetAxleCounterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *block_section_g_id = nullptr) {
  auto block_section_g_id__ = block_section_g_id ? _fbb.CreateString(block_section_g_id) : 0;
  return proto::CreateResetAxleCounter(
      _fbb,
      block_section_g_id__);
}

::flatbuffers::Offset<ResetAxleCounter> CreateResetAxleCounter(::flatbuffers::FlatBufferBuilder &_fbb, const ResetAxleCounterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CommandAckT : public ::flatbuffers::NativeTable {
  typedef CommandAck TableType;
  uint32_t req_seq_id = 0;
  uint32_t event_id = 0;
};

struct CommandAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandAckT NativeTableType;
  typedef CommandAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_SEQ_ID = 4,
    VT_EVENT_ID = 6
  };
  uint32_t req_seq_id() const {
    return GetField<uint32_t>(VT_REQ_SEQ_ID, 0);
  }
  uint32_t event_id() const {
    return GetField<uint32_t>(VT_EVENT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SEQ_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_EVENT_ID, 4) &&
           verifier.EndTable();
  }
  CommandAckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommandAckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommandAck> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommandAckBuilder {
  typedef CommandAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_seq_id(uint32_t req_seq_id) {
    fbb_.AddElement<uint32_t>(CommandAck::VT_REQ_SEQ_ID, req_seq_id, 0);
  }
  void add_event_id(uint32_t event_id) {
    fbb_.AddElement<uint32_t>(CommandAck::VT_EVENT_ID, event_id, 0);
  }
  explicit CommandAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandAck> CreateCommandAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_seq_id = 0,
    uint32_t event_id = 0) {
  CommandAckBuilder builder_(_fbb);
  builder_.add_event_id(event_id);
  builder_.add_req_seq_id(req_seq_id);
  return builder_.Finish();
}

::flatbuffers::Offset<CommandAck> CreateCommandAck(::flatbuffers::FlatBufferBuilder &_fbb, const CommandAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CommandNakT : public ::flatbuffers::NativeTable {
  typedef CommandNak TableType;
  uint32_t req_seq_id = 0;
  proto::NakReason reason = proto::NakReason_UNSPECIFIED;
  std::string reason_text{};
};

struct CommandNak FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandNakT NativeTableType;
  typedef CommandNakBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_SEQ_ID = 4,
    VT_REASON = 6,
    VT_REASON_TEXT = 8
  };
  uint32_t req_seq_id() const {
    return GetField<uint32_t>(VT_REQ_SEQ_ID, 0);
  }
  proto::NakReason reason() const {
    return static_cast<proto::NakReason>(GetField<int8_t>(VT_REASON, 0));
  }
  const ::flatbuffers::String *reason_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REASON_TEXT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SEQ_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_REASON, 1) &&
           VerifyOffset(verifier, VT_REASON_TEXT) &&
           verifier.VerifyString(reason_text()) &&
           verifier.EndTable();
  }
  CommandNakT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommandNakT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CommandNak> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandNakT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommandNakBuilder {
  typedef CommandNak Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_seq_id(uint32_t req_seq_id) {
    fbb_.AddElement<uint32_t>(CommandNak::VT_REQ_SEQ_ID, req_seq_id, 0);
  }
  void add_reason(proto::NakReason reason) {
    fbb_.AddElement<int8_t>(CommandNak::VT_REASON, static_cast<int8_t>(reason), 0);
  }
  void add_reason_text(::flatbuffers::Offset<::flatbuffers::String> reason_text) {
    fbb_.AddOffset(CommandNak::VT_REASON_TEXT, reason_text);
  }
  explicit CommandNakBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandNak> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandNak>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandNak> CreateCommandNak(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_seq_id = 0,
    proto::NakReason reason = proto::NakReason_UNSPECIFIED,
    ::flatbuffers::Offset<::flatbuffers::String> reason_text = 0) {
  CommandNakBuilder builder_(_fbb);
  builder_.add_reason_text(reason_text);
  builder_.add_req_seq_id(req_seq_id);
  builder_.add_reason(reason);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandNak> CreateCommandNakDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_seq_id = 0,
    proto::NakReason reason = proto::NakReason_UNSPECIFIED,
    const char *reason_text = nullptr) {
  auto reason_text__ = reason_text ? _fbb.CreateString(reason_text) : 0;
  return proto::CreateCommandNak(
      _fbb,
      req_seq_id,
      reason,
      reason_text__);
}

::flatbuffers::Offset<CommandNak> CreateCommandNak(::flatbuffers::FlatBufferBuilder &_fbb, const CommandNakT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SetSwitchPositionT *SetSwitchPosition::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetSwitchPositionT>(new SetSwitchPositionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetSwitchPosition::UnPackTo(SetSwitchPositionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = position(); _o->position = _e; }
}

inline ::flatbuffers::Offset<SetSwitchPosition> CreateSetSwitchPosition(::flatbuffers::FlatBufferBuilder &_fbb, const SetSwitchPositionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetSwitchPosition::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetSwitchPosition> SetSwitchPosition::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSwitchPositionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetSwitchPositionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _position = _o->position;
  return proto::CreateSetSwitchPosition(
      _fbb,
      _g_id,
      _position);
}

inline SetSignalAspectT *SetSignalAspect::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetSignalAspectT>(new SetSignalAspectT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetSignalAspect::UnPackTo(SetSignalAspectT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = aspect(); _o->aspect = _e; }
}

inline ::flatbuffers::Offset<SetSignalAspect> CreateSetSignalAspect(::flatbuffers::FlatBufferBuilder &_fbb, const SetSignalAspectT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetSignalAspect::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetSignalAspect> SetSignalAspect::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetSignalAspectT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetSignalAspectT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _aspect = _o->aspect;
  return proto::CreateSetSignalAspect(
      _fbb,
      _g_id,
      _aspect);
}

inline SetDerailerPositionT *SetDerailerPosition::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetDerailerPositionT>(new SetDerailerPositionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetDerailerPosition::UnPackTo(SetDerailerPositionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = position(); _o->position = _e; }
}

inline ::flatbuffers::Offset<SetDerailerPosition> CreateSetDerailerPosition(::flatbuffers::FlatBufferBuilder &_fbb, const SetDerailerPositionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetDerailerPosition::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetDerailerPosition> SetDerailerPosition::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetDerailerPositionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetDerailerPositionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _position = _o->position;
  return proto::CreateSetDerailerPosition(
      _fbb,
      _g_id,
      _position);
}

inline SetBlockSectionT *SetBlockSection::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetBlockSectionT>(new SetBlockSectionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetBlockSection::UnPackTo(SetBlockSectionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = state(); _o->state = _e; }
}

inline ::flatbuffers::Offset<SetBlockSection> CreateSetBlockSection(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockSectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetBlockSection::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetBlockSection> SetBlockSection::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockSectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetBlockSectionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _state = _o->state;
  return proto::CreateSetBlockSection(
      _fbb,
      _g_id,
      _state);
}

inline RequestRouteT *RequestRoute::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RequestRouteT>(new RequestRouteT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RequestRoute::UnPackTo(RequestRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = from_signal_g_id(); if (_e) _o->from_signal_g_id = _e->str(); }
  { auto _e = to_signal_g_id(); if (_e) _o->to_signal_g_id = _e->str(); }
}

inline ::flatbuffers::Offset<RequestRoute> CreateRequestRoute(::flatbuffers::FlatBufferBuilder &_fbb, const RequestRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return RequestRoute::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RequestRoute> RequestRoute::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RequestRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RequestRouteT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _from_signal_g_id = _fbb.CreateString(_o->from_signal_g_id);
  auto _to_signal_g_id = _fbb.CreateString(_o->to_signal_g_id);
  return proto::CreateRequestRoute(
      _fbb,
      _from_signal_g_id,
      _to_signal_g_id);
}

inline CancelRouteT *CancelRoute::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CancelRouteT>(new CancelRouteT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CancelRoute::UnPackTo(CancelRouteT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = route_id(); if (_e) _o->route_id = _e->str(); }
}

inline ::flatbuffers::Offset<CancelRoute> CreateCancelRoute(::flatbuffers::FlatBufferBuilder &_fbb, const CancelRouteT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CancelRoute::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CancelRoute> CancelRoute::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CancelRouteT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CancelRouteT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _route_id = _fbb.CreateString(_o->route_id);
  return proto::CreateCancelRoute(
      _fbb,
      _route_id);
}

inline AcknowledgeAlarmT *AcknowledgeAlarm::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AcknowledgeAlarmT>(new AcknowledgeAlarmT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AcknowledgeAlarm::UnPackTo(AcknowledgeAlarmT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = alarm_id(); if (_e) _o->alarm_id = _e->str(); }
}

inline ::flatbuffers::Offset<AcknowledgeAlarm> CreateAcknowledgeAlarm(::flatbuffers::FlatBufferBuilder &_fbb, const AcknowledgeAlarmT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return AcknowledgeAlarm::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AcknowledgeAlarm> AcknowledgeAlarm::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AcknowledgeAlarmT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AcknowledgeAlarmT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _alarm_id = _fbb.CreateString(_o->alarm_id);
  return proto::CreateAcknowledgeAlarm(
      _fbb,
      _alarm_id);
}

inline SetBlockDirectionT *SetBlockDirection::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SetBlockDirectionT>(new SetBlockDirectionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SetBlockDirection::UnPackTo(SetBlockDirectionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_section_g_id(); if (_e) _o->block_section_g_id = _e->str(); }
  { auto _e = operation(); _o->operation = _e; }
}

inline ::flatbuffers::Offset<SetBlockDirection> CreateSetBlockDirection(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockDirectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SetBlockDirection::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SetBlockDirection> SetBlockDirection::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SetBlockDirectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SetBlockDirectionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_section_g_id = _fbb.CreateString(_o->block_section_g_id);
  auto _operation = _o->operation;
  return proto::CreateSetBlockDirection(
      _fbb,
      _block_section_g_id,
      _operation);
}

inline InitAxleCounterResetT *InitAxleCounterReset::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<InitAxleCounterResetT>(new InitAxleCounterResetT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InitAxleCounterReset::UnPackTo(InitAxleCounterResetT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_section_g_id(); if (_e) _o->block_section_g_id = _e->str(); }
}

inline ::flatbuffers::Offset<InitAxleCounterReset> CreateInitAxleCounterReset(::flatbuffers::FlatBufferBuilder &_fbb, const InitAxleCounterResetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return InitAxleCounterReset::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InitAxleCounterReset> InitAxleCounterReset::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InitAxleCounterResetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InitAxleCounterResetT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_section_g_id = _fbb.CreateString(_o->block_section_g_id);
  return proto::CreateInitAxleCounterReset(
      _fbb,
      _block_section_g_id);
}

inline ResetAxleCounterT *ResetAxleCounter::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ResetAxleCounterT>(new ResetAxleCounterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ResetAxleCounter::UnPackTo(ResetAxleCounterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = block_section_g_id(); if (_e) _o->block_section_g_id = _e->str(); }
}

inline ::flatbuffers::Offset<ResetAxleCounter> CreateResetAxleCounter(::flatbuffers::FlatBufferBuilder &_fbb, const ResetAxleCounterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ResetAxleCounter::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ResetAxleCounter> ResetAxleCounter::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ResetAxleCounterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ResetAxleCounterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _block_section_g_id = _fbb.CreateString(_o->block_section_g_id);
  return proto::CreateResetAxleCounter(
      _fbb,
      _block_section_g_id);
}

inline CommandAckT *CommandAck::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CommandAckT>(new CommandAckT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommandAck::UnPackTo(CommandAckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = req_seq_id(); _o->req_seq_id = _e; }
  { auto _e = event_id(); _o->event_id = _e; }
}

inline ::flatbuffers::Offset<CommandAck> CreateCommandAck(::flatbuffers::FlatBufferBuilder &_fbb, const CommandAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CommandAck::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommandAck> CommandAck::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommandAckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _req_seq_id = _o->req_seq_id;
  auto _event_id = _o->event_id;
  return proto::CreateCommandAck(
      _fbb,
      _req_seq_id,
      _event_id);
}

inline CommandNakT *CommandNak::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<CommandNakT>(new CommandNakT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CommandNak::UnPackTo(CommandNakT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = req_seq_id(); _o->req_seq_id = _e; }
  { auto _e = reason(); _o->reason = _e; }
  { auto _e = reason_text(); if (_e) _o->reason_text = _e->str(); }
}

inline ::flatbuffers::Offset<CommandNak> CreateCommandNak(::flatbuffers::FlatBufferBuilder &_fbb, const CommandNakT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CommandNak::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CommandNak> CommandNak::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CommandNakT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CommandNakT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _req_seq_id = _o->req_seq_id;
  auto _reason = _o->reason;
  auto _reason_text = _o->reason_text.empty() ? 0 : _fbb.CreateString(_o->reason_text);
  return proto::CreateCommandNak(
      _fbb,
      _req_seq_id,
      _reason,
      _reason_text);
}

inline const proto::CommandNak *GetCommandNak(const void *buf) {
  return ::flatbuffers::GetRoot<proto::CommandNak>(buf);
}

inline const proto::CommandNak *GetSizePrefixedCommandNak(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proto::CommandNak>(buf);
}

template <bool B = false>
inline bool VerifyCommandNakBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<proto::CommandNak>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedCommandNakBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<proto::CommandNak>(nullptr);
}

inline void FinishCommandNakBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::CommandNak> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCommandNakBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::CommandNak> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::CommandNakT> UnPackCommandNak(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::CommandNakT>(GetCommandNak(buf)->UnPack(res));
}

inline std::unique_ptr<proto::CommandNakT> UnPackSizePrefixedCommandNak(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::CommandNakT>(GetSizePrefixedCommandNak(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_COMMANDS_PROTO_H_
