// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EVENTS_PROTO_H_
#define FLATBUFFERS_GENERATED_EVENTS_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace proto {

struct SwitchPositionChanged;
struct SwitchPositionChangedBuilder;
struct SwitchPositionChangedT;

struct SwitchOccupancyChanged;
struct SwitchOccupancyChangedBuilder;
struct SwitchOccupancyChangedT;

struct SignalAspectChanged;
struct SignalAspectChangedBuilder;
struct SignalAspectChangedT;

struct TrackSectionOccupancyChanged;
struct TrackSectionOccupancyChangedBuilder;
struct TrackSectionOccupancyChangedT;

struct DerailerPositionChanged;
struct DerailerPositionChangedBuilder;
struct DerailerPositionChangedT;

struct BlockSectionStateChanged;
struct BlockSectionStateChangedBuilder;
struct BlockSectionStateChangedT;

struct RouteSet;
struct RouteSetBuilder;
struct RouteSetT;

struct RouteReleased;
struct RouteReleasedBuilder;
struct RouteReleasedT;

struct TrainMovement;
struct TrainMovementBuilder;
struct TrainMovementT;

struct AlarmRaised;
struct AlarmRaisedBuilder;
struct AlarmRaisedT;

struct AlarmCleared;
struct AlarmClearedBuilder;
struct AlarmClearedT;

struct DispatchAreaOwnershipChanged;
struct DispatchAreaOwnershipChangedBuilder;
struct DispatchAreaOwnershipChangedT;

struct SessionStateChanged;
struct SessionStateChangedBuilder;
struct SessionStateChangedT;

struct TrainComposed;
struct TrainComposedBuilder;
struct TrainComposedT;

struct TrainDecomposed;
struct TrainDecomposedBuilder;
struct TrainDecomposedT;

struct BlockDirectionStateChanged;
struct BlockDirectionStateChangedBuilder;
struct BlockDirectionStateChangedT;

enum RouteReleaseReason : int8_t {
  RouteReleaseReason_TRAIN_CLEARED = 0,
  RouteReleaseReason_OPERATOR_CANCEL = 1,
  RouteReleaseReason_TIMEOUT = 2,
  RouteReleaseReason_CONFLICT = 3,
  RouteReleaseReason_MIN = RouteReleaseReason_TRAIN_CLEARED,
  RouteReleaseReason_MAX = RouteReleaseReason_CONFLICT
};

inline const RouteReleaseReason (&EnumValuesRouteReleaseReason())[4] {
  static const RouteReleaseReason values[] = {
    RouteReleaseReason_TRAIN_CLEARED,
    RouteReleaseReason_OPERATOR_CANCEL,
    RouteReleaseReason_TIMEOUT,
    RouteReleaseReason_CONFLICT
  };
  return values;
}

inline const char * const *EnumNamesRouteReleaseReason() {
  static const char * const names[5] = {
    "TRAIN_CLEARED",
    "OPERATOR_CANCEL",
    "TIMEOUT",
    "CONFLICT",
    nullptr
  };
  return names;
}

inline const char *EnumNameRouteReleaseReason(RouteReleaseReason e) {
  if (::flatbuffers::IsOutRange(e, RouteReleaseReason_TRAIN_CLEARED, RouteReleaseReason_CONFLICT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRouteReleaseReason()[index];
}

enum Direction : int8_t {
  Direction_FORWARD = 0,
  Direction_BACKWARD = 1,
  Direction_MIN = Direction_FORWARD,
  Direction_MAX = Direction_BACKWARD
};

inline const Direction (&EnumValuesDirection())[2] {
  static const Direction values[] = {
    Direction_FORWARD,
    Direction_BACKWARD
  };
  return values;
}

inline const char * const *EnumNamesDirection() {
  static const char * const names[3] = {
    "FORWARD",
    "BACKWARD",
    nullptr
  };
  return names;
}

inline const char *EnumNameDirection(Direction e) {
  if (::flatbuffers::IsOutRange(e, Direction_FORWARD, Direction_BACKWARD)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDirection()[index];
}

enum AlarmType : int8_t {
  AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY = 0,
  AlarmType_SWITCH_POSITION_MISMATCH = 1,
  AlarmType_SIGNAL_OVERRUN = 2,
  AlarmType_DERAILER_CONFLICT = 3,
  AlarmType_COMMS_FAILURE = 4,
  AlarmType_ENGINE_FAULT = 5,
  AlarmType_MIN = AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY,
  AlarmType_MAX = AlarmType_ENGINE_FAULT
};

inline const AlarmType (&EnumValuesAlarmType())[6] {
  static const AlarmType values[] = {
    AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY,
    AlarmType_SWITCH_POSITION_MISMATCH,
    AlarmType_SIGNAL_OVERRUN,
    AlarmType_DERAILER_CONFLICT,
    AlarmType_COMMS_FAILURE,
    AlarmType_ENGINE_FAULT
  };
  return values;
}

inline const char * const *EnumNamesAlarmType() {
  static const char * const names[7] = {
    "TRACK_OCCUPIED_UNEXPECTEDLY",
    "SWITCH_POSITION_MISMATCH",
    "SIGNAL_OVERRUN",
    "DERAILER_CONFLICT",
    "COMMS_FAILURE",
    "ENGINE_FAULT",
    nullptr
  };
  return names;
}

inline const char *EnumNameAlarmType(AlarmType e) {
  if (::flatbuffers::IsOutRange(e, AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY, AlarmType_ENGINE_FAULT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAlarmType()[index];
}

enum TrainDecomposeReason : int8_t {
  TrainDecomposeReason_UNCOUPLED = 0,
  TrainDecomposeReason_SCENARIO_RESET = 1,
  TrainDecomposeReason_DERAILED = 2,
  TrainDecomposeReason_MIN = TrainDecomposeReason_UNCOUPLED,
  TrainDecomposeReason_MAX = TrainDecomposeReason_DERAILED
};

inline const TrainDecomposeReason (&EnumValuesTrainDecomposeReason())[3] {
  static const TrainDecomposeReason values[] = {
    TrainDecomposeReason_UNCOUPLED,
    TrainDecomposeReason_SCENARIO_RESET,
    TrainDecomposeReason_DERAILED
  };
  return values;
}

inline const char * const *EnumNamesTrainDecomposeReason() {
  static const char * const names[4] = {
    "UNCOUPLED",
    "SCENARIO_RESET",
    "DERAILED",
    nullptr
  };
  return names;
}

inline const char *EnumNameTrainDecomposeReason(TrainDecomposeReason e) {
  if (::flatbuffers::IsOutRange(e, TrainDecomposeReason_UNCOUPLED, TrainDecomposeReason_DERAILED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTrainDecomposeReason()[index];
}

struct SwitchPositionChangedT : public ::flatbuffers::NativeTable {
  typedef SwitchPositionChanged TableType;
  std::string g_id{};
  proto::SwitchPosition new_position = proto::SwitchPosition_STRAIGHT;
  proto::ChangeCause cause = proto::ChangeCause_COMMAND;
};

struct SwitchPositionChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SwitchPositionChangedT NativeTableType;
  typedef SwitchPositionChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_NEW_POSITION = 6,
    VT_CAUSE = 8
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::SwitchPosition new_position() const {
    return static_cast<proto::SwitchPosition>(GetField<int8_t>(VT_NEW_POSITION, 0));
  }
  proto::ChangeCause cause() const {
    return static_cast<proto::ChangeCause>(GetField<int8_t>(VT_CAUSE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_NEW_POSITION, 1) &&
           VerifyField<int8_t>(verifier, VT_CAUSE, 1) &&
           verifier.EndTable();
  }
  SwitchPositionChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SwitchPositionChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SwitchPositionChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchPositionChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SwitchPositionChangedBuilder {
  typedef SwitchPositionChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SwitchPositionChanged::VT_G_ID, g_id);
  }
  void add_new_position(proto::SwitchPosition new_position) {
    fbb_.AddElement<int8_t>(SwitchPositionChanged::VT_NEW_POSITION, static_cast<int8_t>(new_position), 0);
  }
  void add_cause(proto::ChangeCause cause) {
    fbb_.AddElement<int8_t>(SwitchPositionChanged::VT_CAUSE, static_cast<int8_t>(cause), 0);
  }
  explicit SwitchPositionChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SwitchPositionChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SwitchPositionChanged>(end);
    fbb_.Required(o, SwitchPositionChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SwitchPositionChanged> CreateSwitchPositionChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::SwitchPosition new_position = proto::SwitchPosition_STRAIGHT,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  SwitchPositionChangedBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_cause(cause);
  builder_.add_new_position(new_position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SwitchPositionChanged> CreateSwitchPositionChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::SwitchPosition new_position = proto::SwitchPosition_STRAIGHT,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSwitchPositionChanged(
      _fbb,
      g_id__,
      new_position,
      cause);
}

::flatbuffers::Offset<SwitchPositionChanged> CreateSwitchPositionChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchPositionChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SwitchOccupancyChangedT : public ::flatbuffers::NativeTable {
  typedef SwitchOccupancyChanged TableType;
  std::string g_id{};
  bool occupied = false;
  int32_t axle_count = 0;
  std::string train_g_id{};
};

struct SwitchOccupancyChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SwitchOccupancyChangedT NativeTableType;
  typedef SwitchOccupancyChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_OCCUPIED = 6,
    VT_AXLE_COUNT = 8,
    VT_TRAIN_G_ID = 10
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  bool occupied() const {
    return GetField<uint8_t>(VT_OCCUPIED, 0) != 0;
  }
  int32_t axle_count() const {
    return GetField<int32_t>(VT_AXLE_COUNT, 0);
  }
  const ::flatbuffers::String *train_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_G_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<uint8_t>(verifier, VT_OCCUPIED, 1) &&
           VerifyField<int32_t>(verifier, VT_AXLE_COUNT, 4) &&
           VerifyOffset(verifier, VT_TRAIN_G_ID) &&
           verifier.VerifyString(train_g_id()) &&
           verifier.EndTable();
  }
  SwitchOccupancyChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SwitchOccupancyChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SwitchOccupancyChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchOccupancyChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SwitchOccupancyChangedBuilder {
  typedef SwitchOccupancyChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SwitchOccupancyChanged::VT_G_ID, g_id);
  }
  void add_occupied(bool occupied) {
    fbb_.AddElement<uint8_t>(SwitchOccupancyChanged::VT_OCCUPIED, static_cast<uint8_t>(occupied), 0);
  }
  void add_axle_count(int32_t axle_count) {
    fbb_.AddElement<int32_t>(SwitchOccupancyChanged::VT_AXLE_COUNT, axle_count, 0);
  }
  void add_train_g_id(::flatbuffers::Offset<::flatbuffers::String> train_g_id) {
    fbb_.AddOffset(SwitchOccupancyChanged::VT_TRAIN_G_ID, train_g_id);
  }
  explicit SwitchOccupancyChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SwitchOccupancyChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SwitchOccupancyChanged>(end);
    fbb_.Required(o, SwitchOccupancyChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SwitchOccupancyChanged> CreateSwitchOccupancyChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    bool occupied = false,
    int32_t axle_count = 0,
    ::flatbuffers::Offset<::flatbuffers::String> train_g_id = 0) {
  SwitchOccupancyChangedBuilder builder_(_fbb);
  builder_.add_train_g_id(train_g_id);
  builder_.add_axle_count(axle_count);
  builder_.add_g_id(g_id);
  builder_.add_occupied(occupied);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SwitchOccupancyChanged> CreateSwitchOccupancyChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    bool occupied = false,
    int32_t axle_count = 0,
    const char *train_g_id = nullptr) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  auto train_g_id__ = train_g_id ? _fbb.CreateString(train_g_id) : 0;
  return proto::CreateSwitchOccupancyChanged(
      _fbb,
      g_id__,
      occupied,
      axle_count,
      train_g_id__);
}

::flatbuffers::Offset<SwitchOccupancyChanged> CreateSwitchOccupancyChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchOccupancyChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SignalAspectChangedT : public ::flatbuffers::NativeTable {
  typedef SignalAspectChanged TableType;
  std::string g_id{};
  proto::Aspect new_aspect = proto::Aspect_S1_STOP;
  proto::ChangeCause cause = proto::ChangeCause_COMMAND;
};

struct SignalAspectChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SignalAspectChangedT NativeTableType;
  typedef SignalAspectChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_NEW_ASPECT = 6,
    VT_CAUSE = 8
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::Aspect new_aspect() const {
    return static_cast<proto::Aspect>(GetField<int8_t>(VT_NEW_ASPECT, 0));
  }
  proto::ChangeCause cause() const {
    return static_cast<proto::ChangeCause>(GetField<int8_t>(VT_CAUSE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_NEW_ASPECT, 1) &&
           VerifyField<int8_t>(verifier, VT_CAUSE, 1) &&
           verifier.EndTable();
  }
  SignalAspectChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SignalAspectChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SignalAspectChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SignalAspectChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SignalAspectChangedBuilder {
  typedef SignalAspectChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(SignalAspectChanged::VT_G_ID, g_id);
  }
  void add_new_aspect(proto::Aspect new_aspect) {
    fbb_.AddElement<int8_t>(SignalAspectChanged::VT_NEW_ASPECT, static_cast<int8_t>(new_aspect), 0);
  }
  void add_cause(proto::ChangeCause cause) {
    fbb_.AddElement<int8_t>(SignalAspectChanged::VT_CAUSE, static_cast<int8_t>(cause), 0);
  }
  explicit SignalAspectChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SignalAspectChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SignalAspectChanged>(end);
    fbb_.Required(o, SignalAspectChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<SignalAspectChanged> CreateSignalAspectChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::Aspect new_aspect = proto::Aspect_S1_STOP,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  SignalAspectChangedBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_cause(cause);
  builder_.add_new_aspect(new_aspect);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SignalAspectChanged> CreateSignalAspectChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::Aspect new_aspect = proto::Aspect_S1_STOP,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateSignalAspectChanged(
      _fbb,
      g_id__,
      new_aspect,
      cause);
}

::flatbuffers::Offset<SignalAspectChanged> CreateSignalAspectChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SignalAspectChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TrackSectionOccupancyChangedT : public ::flatbuffers::NativeTable {
  typedef TrackSectionOccupancyChanged TableType;
  std::string g_id{};
  bool occupied = false;
  int32_t axle_count = 0;
  std::string train_g_id{};
};

struct TrackSectionOccupancyChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrackSectionOccupancyChangedT NativeTableType;
  typedef TrackSectionOccupancyChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_OCCUPIED = 6,
    VT_AXLE_COUNT = 8,
    VT_TRAIN_G_ID = 10
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  bool occupied() const {
    return GetField<uint8_t>(VT_OCCUPIED, 0) != 0;
  }
  int32_t axle_count() const {
    return GetField<int32_t>(VT_AXLE_COUNT, 0);
  }
  const ::flatbuffers::String *train_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_G_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<uint8_t>(verifier, VT_OCCUPIED, 1) &&
           VerifyField<int32_t>(verifier, VT_AXLE_COUNT, 4) &&
           VerifyOffset(verifier, VT_TRAIN_G_ID) &&
           verifier.VerifyString(train_g_id()) &&
           verifier.EndTable();
  }
  TrackSectionOccupancyChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TrackSectionOccupancyChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TrackSectionOccupancyChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrackSectionOccupancyChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TrackSectionOccupancyChangedBuilder {
  typedef TrackSectionOccupancyChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(TrackSectionOccupancyChanged::VT_G_ID, g_id);
  }
  void add_occupied(bool occupied) {
    fbb_.AddElement<uint8_t>(TrackSectionOccupancyChanged::VT_OCCUPIED, static_cast<uint8_t>(occupied), 0);
  }
  void add_axle_count(int32_t axle_count) {
    fbb_.AddElement<int32_t>(TrackSectionOccupancyChanged::VT_AXLE_COUNT, axle_count, 0);
  }
  void add_train_g_id(::flatbuffers::Offset<::flatbuffers::String> train_g_id) {
    fbb_.AddOffset(TrackSectionOccupancyChanged::VT_TRAIN_G_ID, train_g_id);
  }
  explicit TrackSectionOccupancyChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrackSectionOccupancyChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrackSectionOccupancyChanged>(end);
    fbb_.Required(o, TrackSectionOccupancyChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrackSectionOccupancyChanged> CreateTrackSectionOccupancyChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    bool occupied = false,
    int32_t axle_count = 0,
    ::flatbuffers::Offset<::flatbuffers::String> train_g_id = 0) {
  TrackSectionOccupancyChangedBuilder builder_(_fbb);
  builder_.add_train_g_id(train_g_id);
  builder_.add_axle_count(axle_count);
  builder_.add_g_id(g_id);
  builder_.add_occupied(occupied);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrackSectionOccupancyChanged> CreateTrackSectionOccupancyChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    bool occupied = false,
    int32_t axle_count = 0,
    const char *train_g_id = nullptr) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  auto train_g_id__ = train_g_id ? _fbb.CreateString(train_g_id) : 0;
  return proto::CreateTrackSectionOccupancyChanged(
      _fbb,
      g_id__,
      occupied,
      axle_count,
      train_g_id__);
}

::flatbuffers::Offset<TrackSectionOccupancyChanged> CreateTrackSectionOccupancyChanged(::flatbuffers::FlatBufferBuilder &_fbb, const TrackSectionOccupancyChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DerailerPositionChangedT : public ::flatbuffers::NativeTable {
  typedef DerailerPositionChanged TableType;
  std::string g_id{};
  proto::DerailerPosition new_position = proto::DerailerPosition_LOCKED;
  proto::ChangeCause cause = proto::ChangeCause_COMMAND;
};

struct DerailerPositionChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DerailerPositionChangedT NativeTableType;
  typedef DerailerPositionChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_NEW_POSITION = 6,
    VT_CAUSE = 8
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::DerailerPosition new_position() const {
    return static_cast<proto::DerailerPosition>(GetField<int8_t>(VT_NEW_POSITION, 0));
  }
  proto::ChangeCause cause() const {
    return static_cast<proto::ChangeCause>(GetField<int8_t>(VT_CAUSE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_NEW_POSITION, 1) &&
           VerifyField<int8_t>(verifier, VT_CAUSE, 1) &&
           verifier.EndTable();
  }
  DerailerPositionChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DerailerPositionChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DerailerPositionChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DerailerPositionChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DerailerPositionChangedBuilder {
  typedef DerailerPositionChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(DerailerPositionChanged::VT_G_ID, g_id);
  }
  void add_new_position(proto::DerailerPosition new_position) {
    fbb_.AddElement<int8_t>(DerailerPositionChanged::VT_NEW_POSITION, static_cast<int8_t>(new_position), 0);
  }
  void add_cause(proto::ChangeCause cause) {
    fbb_.AddElement<int8_t>(DerailerPositionChanged::VT_CAUSE, static_cast<int8_t>(cause), 0);
  }
  explicit DerailerPositionChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DerailerPositionChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DerailerPositionChanged>(end);
    fbb_.Required(o, DerailerPositionChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<DerailerPositionChanged> CreateDerailerPositionChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::DerailerPosition new_position = proto::DerailerPosition_LOCKED,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  DerailerPositionChangedBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_cause(cause);
  builder_.add_new_position(new_position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DerailerPositionChanged> CreateDerailerPositionChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::DerailerPosition new_position = proto::DerailerPosition_LOCKED,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateDerailerPositionChanged(
      _fbb,
      g_id__,
      new_position,
      cause);
}

::flatbuffers::Offset<DerailerPositionChanged> CreateDerailerPositionChanged(::flatbuffers::FlatBufferBuilder &_fbb, const DerailerPositionChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockSectionStateChangedT : public ::flatbuffers::NativeTable {
  typedef BlockSectionStateChanged TableType;
  std::string g_id{};
  proto::BlockSectionState new_state = proto::BlockSectionState_OPEN;
};

struct BlockSectionStateChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockSectionStateChangedT NativeTableType;
  typedef BlockSectionStateChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_NEW_STATE = 6
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::BlockSectionState new_state() const {
    return static_cast<proto::BlockSectionState>(GetField<int8_t>(VT_NEW_STATE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_NEW_STATE, 1) &&
           verifier.EndTable();
  }
  BlockSectionStateChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockSectionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockSectionStateChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockSectionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockSectionStateChangedBuilder {
  typedef BlockSectionStateChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(BlockSectionStateChanged::VT_G_ID, g_id);
  }
  void add_new_state(proto::BlockSectionState new_state) {
    fbb_.AddElement<int8_t>(BlockSectionStateChanged::VT_NEW_STATE, static_cast<int8_t>(new_state), 0);
  }
  explicit BlockSectionStateChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockSectionStateChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockSectionStateChanged>(end);
    fbb_.Required(o, BlockSectionStateChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockSectionStateChanged> CreateBlockSectionStateChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::BlockSectionState new_state = proto::BlockSectionState_OPEN) {
  BlockSectionStateChangedBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_new_state(new_state);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockSectionStateChanged> CreateBlockSectionStateChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::BlockSectionState new_state = proto::BlockSectionState_OPEN) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateBlockSectionStateChanged(
      _fbb,
      g_id__,
      new_state);
}

::flatbuffers::Offset<BlockSectionStateChanged> CreateBlockSectionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const BlockSectionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RouteSetT : public ::flatbuffers::NativeTable {
  typedef RouteSet TableType;
  std::string route_id{};
  std::string from_g_id{};
  std::string to_g_id{};
  std::vector<std::string> section_ids{};
};

struct RouteSet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RouteSetT NativeTableType;
  typedef RouteSetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROUTE_ID = 4,
    VT_FROM_G_ID = 6,
    VT_TO_G_ID = 8,
    VT_SECTION_IDS = 10
  };
  const ::flatbuffers::String *route_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROUTE_ID);
  }
  const ::flatbuffers::String *from_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FROM_G_ID);
  }
  const ::flatbuffers::String *to_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TO_G_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *section_ids() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SECTION_IDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ROUTE_ID) &&
           verifier.VerifyString(route_id()) &&
           VerifyOffsetRequired(verifier, VT_FROM_G_ID) &&
           verifier.VerifyString(from_g_id()) &&
           VerifyOffsetRequired(verifier, VT_TO_G_ID) &&
           verifier.VerifyString(to_g_id()) &&
           VerifyOffset(verifier, VT_SECTION_IDS) &&
           verifier.VerifyVector(section_ids()) &&
           verifier.VerifyVectorOfStrings(section_ids()) &&
           verifier.EndTable();
  }
  RouteSetT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RouteSetT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RouteSet> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RouteSetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RouteSetBuilder {
  typedef RouteSet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_route_id(::flatbuffers::Offset<::flatbuffers::String> route_id) {
    fbb_.AddOffset(RouteSet::VT_ROUTE_ID, route_id);
  }
  void add_from_g_id(::flatbuffers::Offset<::flatbuffers::String> from_g_id) {
    fbb_.AddOffset(RouteSet::VT_FROM_G_ID, from_g_id);
  }
  void add_to_g_id(::flatbuffers::Offset<::flatbuffers::String> to_g_id) {
    fbb_.AddOffset(RouteSet::VT_TO_G_ID, to_g_id);
  }
  void add_section_ids(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> section_ids) {
    fbb_.AddOffset(RouteSet::VT_SECTION_IDS, section_ids);
  }
  explicit RouteSetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RouteSet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RouteSet>(end);
    fbb_.Required(o, RouteSet::VT_ROUTE_ID);
    fbb_.Required(o, RouteSet::VT_FROM_G_ID);
    fbb_.Required(o, RouteSet::VT_TO_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<RouteSet> CreateRouteSet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> route_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> from_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> to_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> section_ids = 0) {
  RouteSetBuilder builder_(_fbb);
  builder_.add_section_ids(section_ids);
  builder_.add_to_g_id(to_g_id);
  builder_.add_from_g_id(from_g_id);
  builder_.add_route_id(route_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RouteSet> CreateRouteSetDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *route_id = nullptr,
    const char *from_g_id = nullptr,
    const char *to_g_id = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *section_ids = nullptr) {
  auto route_id__ = route_id ? _fbb.CreateString(route_id) : 0;
  auto from_g_id__ = from_g_id ? _fbb.CreateString(from_g_id) : 0;
  auto to_g_id__ = to_g_id ? _fbb.CreateString(to_g_id) : 0;
  auto section_ids__ = section_ids ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*section_ids) : 0;
  return proto::CreateRouteSet(
      _fbb,
      route_id__,
      from_g_id__,
      to_g_id__,
      section_ids__);
}

::flatbuffers::Offset<RouteSet> CreateRouteSet(::flatbuffers::FlatBufferBuilder &_fbb, const RouteSetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RouteReleasedT : public ::flatbuffers::NativeTable {
  typedef RouteReleased TableType;
  std::string route_id{};
  proto::RouteReleaseReason reason = proto::RouteReleaseReason_TRAIN_CLEARED;
};

struct RouteReleased FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RouteReleasedT NativeTableType;
  typedef RouteReleasedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROUTE_ID = 4,
    VT_REASON = 6
  };
  const ::flatbuffers::String *route_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ROUTE_ID);
  }
  proto::RouteReleaseReason reason() const {
    return static_cast<proto::RouteReleaseReason>(GetField<int8_t>(VT_REASON, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ROUTE_ID) &&
           verifier.VerifyString(route_id()) &&
           VerifyField<int8_t>(verifier, VT_REASON, 1) &&
           verifier.EndTable();
  }
  RouteReleasedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RouteReleasedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RouteReleased> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RouteReleasedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RouteReleasedBuilder {
  typedef RouteReleased Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_route_id(::flatbuffers::Offset<::flatbuffers::String> route_id) {
    fbb_.AddOffset(RouteReleased::VT_ROUTE_ID, route_id);
  }
  void add_reason(proto::RouteReleaseReason reason) {
    fbb_.AddElement<int8_t>(RouteReleased::VT_REASON, static_cast<int8_t>(reason), 0);
  }
  explicit RouteReleasedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RouteReleased> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RouteReleased>(end);
    fbb_.Required(o, RouteReleased::VT_ROUTE_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<RouteReleased> CreateRouteReleased(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> route_id = 0,
    proto::RouteReleaseReason reason = proto::RouteReleaseReason_TRAIN_CLEARED) {
  RouteReleasedBuilder builder_(_fbb);
  builder_.add_route_id(route_id);
  builder_.add_reason(reason);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RouteReleased> CreateRouteReleasedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *route_id = nullptr,
    proto::RouteReleaseReason reason = proto::RouteReleaseReason_TRAIN_CLEARED) {
  auto route_id__ = route_id ? _fbb.CreateString(route_id) : 0;
  return proto::CreateRouteReleased(
      _fbb,
      route_id__,
      reason);
}

::flatbuffers::Offset<RouteReleased> CreateRouteReleased(::flatbuffers::FlatBufferBuilder &_fbb, const RouteReleasedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TrainMovementT : public ::flatbuffers::NativeTable {
  typedef TrainMovement TableType;
  std::string train_g_id{};
  std::string section_g_id{};
  proto::Direction direction = proto::Direction_FORWARD;
  float speed_kmh = 0.0f;
};

struct TrainMovement FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainMovementT NativeTableType;
  typedef TrainMovementBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRAIN_G_ID = 4,
    VT_SECTION_G_ID = 6,
    VT_DIRECTION = 8,
    VT_SPEED_KMH = 10
  };
  const ::flatbuffers::String *train_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_G_ID);
  }
  const ::flatbuffers::String *section_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECTION_G_ID);
  }
  proto::Direction direction() const {
    return static_cast<proto::Direction>(GetField<int8_t>(VT_DIRECTION, 0));
  }
  float speed_kmh() const {
    return GetField<float>(VT_SPEED_KMH, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRAIN_G_ID) &&
           verifier.VerifyString(train_g_id()) &&
           VerifyOffsetRequired(verifier, VT_SECTION_G_ID) &&
           verifier.VerifyString(section_g_id()) &&
           VerifyField<int8_t>(verifier, VT_DIRECTION, 1) &&
           VerifyField<float>(verifier, VT_SPEED_KMH, 4) &&
           verifier.EndTable();
  }
  TrainMovementT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TrainMovementT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TrainMovement> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainMovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TrainMovementBuilder {
  typedef TrainMovement Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_train_g_id(::flatbuffers::Offset<::flatbuffers::String> train_g_id) {
    fbb_.AddOffset(TrainMovement::VT_TRAIN_G_ID, train_g_id);
  }
  void add_section_g_id(::flatbuffers::Offset<::flatbuffers::String> section_g_id) {
    fbb_.AddOffset(TrainMovement::VT_SECTION_G_ID, section_g_id);
  }
  void add_direction(proto::Direction direction) {
    fbb_.AddElement<int8_t>(TrainMovement::VT_DIRECTION, static_cast<int8_t>(direction), 0);
  }
  void add_speed_kmh(float speed_kmh) {
    fbb_.AddElement<float>(TrainMovement::VT_SPEED_KMH, speed_kmh, 0.0f);
  }
  explicit TrainMovementBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainMovement> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainMovement>(end);
    fbb_.Required(o, TrainMovement::VT_TRAIN_G_ID);
    fbb_.Required(o, TrainMovement::VT_SECTION_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainMovement> CreateTrainMovement(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> train_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> section_g_id = 0,
    proto::Direction direction = proto::Direction_FORWARD,
    float speed_kmh = 0.0f) {
  TrainMovementBuilder builder_(_fbb);
  builder_.add_speed_kmh(speed_kmh);
  builder_.add_section_g_id(section_g_id);
  builder_.add_train_g_id(train_g_id);
  builder_.add_direction(direction);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainMovement> CreateTrainMovementDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *train_g_id = nullptr,
    const char *section_g_id = nullptr,
    proto::Direction direction = proto::Direction_FORWARD,
    float speed_kmh = 0.0f) {
  auto train_g_id__ = train_g_id ? _fbb.CreateString(train_g_id) : 0;
  auto section_g_id__ = section_g_id ? _fbb.CreateString(section_g_id) : 0;
  return proto::CreateTrainMovement(
      _fbb,
      train_g_id__,
      section_g_id__,
      direction,
      speed_kmh);
}

::flatbuffers::Offset<TrainMovement> CreateTrainMovement(::flatbuffers::FlatBufferBuilder &_fbb, const TrainMovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AlarmRaisedT : public ::flatbuffers::NativeTable {
  typedef AlarmRaised TableType;
  std::string alarm_id{};
  proto::AlarmType alarm_type = proto::AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY;
  std::string object_g_id{};
  std::string message{};
};

struct AlarmRaised FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AlarmRaisedT NativeTableType;
  typedef AlarmRaisedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ALARM_ID = 4,
    VT_ALARM_TYPE = 6,
    VT_OBJECT_G_ID = 8,
    VT_MESSAGE = 10
  };
  const ::flatbuffers::String *alarm_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALARM_ID);
  }
  proto::AlarmType alarm_type() const {
    return static_cast<proto::AlarmType>(GetField<int8_t>(VT_ALARM_TYPE, 0));
  }
  const ::flatbuffers::String *object_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OBJECT_G_ID);
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ALARM_ID) &&
           verifier.VerifyString(alarm_id()) &&
           VerifyField<int8_t>(verifier, VT_ALARM_TYPE, 1) &&
           VerifyOffset(verifier, VT_OBJECT_G_ID) &&
           verifier.VerifyString(object_g_id()) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  AlarmRaisedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AlarmRaisedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AlarmRaised> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmRaisedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AlarmRaisedBuilder {
  typedef AlarmRaised Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_alarm_id(::flatbuffers::Offset<::flatbuffers::String> alarm_id) {
    fbb_.AddOffset(AlarmRaised::VT_ALARM_ID, alarm_id);
  }
  void add_alarm_type(proto::AlarmType alarm_type) {
    fbb_.AddElement<int8_t>(AlarmRaised::VT_ALARM_TYPE, static_cast<int8_t>(alarm_type), 0);
  }
  void add_object_g_id(::flatbuffers::Offset<::flatbuffers::String> object_g_id) {
    fbb_.AddOffset(AlarmRaised::VT_OBJECT_G_ID, object_g_id);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(AlarmRaised::VT_MESSAGE, message);
  }
  explicit AlarmRaisedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AlarmRaised> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AlarmRaised>(end);
    fbb_.Required(o, AlarmRaised::VT_ALARM_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<AlarmRaised> CreateAlarmRaised(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> alarm_id = 0,
    proto::AlarmType alarm_type = proto::AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY,
    ::flatbuffers::Offset<::flatbuffers::String> object_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  AlarmRaisedBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_object_g_id(object_g_id);
  builder_.add_alarm_id(alarm_id);
  builder_.add_alarm_type(alarm_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AlarmRaised> CreateAlarmRaisedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *alarm_id = nullptr,
    proto::AlarmType alarm_type = proto::AlarmType_TRACK_OCCUPIED_UNEXPECTEDLY,
    const char *object_g_id = nullptr,
    const char *message = nullptr) {
  auto alarm_id__ = alarm_id ? _fbb.CreateString(alarm_id) : 0;
  auto object_g_id__ = object_g_id ? _fbb.CreateString(object_g_id) : 0;
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return proto::CreateAlarmRaised(
      _fbb,
      alarm_id__,
      alarm_type,
      object_g_id__,
      message__);
}

::flatbuffers::Offset<AlarmRaised> CreateAlarmRaised(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmRaisedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AlarmClearedT : public ::flatbuffers::NativeTable {
  typedef AlarmCleared TableType;
  std::string alarm_id{};
};

struct AlarmCleared FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AlarmClearedT NativeTableType;
  typedef AlarmClearedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ALARM_ID = 4
  };
  const ::flatbuffers::String *alarm_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALARM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ALARM_ID) &&
           verifier.VerifyString(alarm_id()) &&
           verifier.EndTable();
  }
  AlarmClearedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AlarmClearedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AlarmCleared> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmClearedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AlarmClearedBuilder {
  typedef AlarmCleared Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_alarm_id(::flatbuffers::Offset<::flatbuffers::String> alarm_id) {
    fbb_.AddOffset(AlarmCleared::VT_ALARM_ID, alarm_id);
  }
  explicit AlarmClearedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AlarmCleared> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AlarmCleared>(end);
    fbb_.Required(o, AlarmCleared::VT_ALARM_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<AlarmCleared> CreateAlarmCleared(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> alarm_id = 0) {
  AlarmClearedBuilder builder_(_fbb);
  builder_.add_alarm_id(alarm_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AlarmCleared> CreateAlarmClearedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *alarm_id = nullptr) {
  auto alarm_id__ = alarm_id ? _fbb.CreateString(alarm_id) : 0;
  return proto::CreateAlarmCleared(
      _fbb,
      alarm_id__);
}

::flatbuffers::Offset<AlarmCleared> CreateAlarmCleared(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmClearedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DispatchAreaOwnershipChangedT : public ::flatbuffers::NativeTable {
  typedef DispatchAreaOwnershipChanged TableType;
  std::string dispatch_area_id{};
  std::string station_sid{};
  std::string new_owner_client_id{};
};

struct DispatchAreaOwnershipChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DispatchAreaOwnershipChangedT NativeTableType;
  typedef DispatchAreaOwnershipChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DISPATCH_AREA_ID = 4,
    VT_STATION_SID = 6,
    VT_NEW_OWNER_CLIENT_ID = 8
  };
  const ::flatbuffers::String *dispatch_area_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPATCH_AREA_ID);
  }
  const ::flatbuffers::String *station_sid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATION_SID);
  }
  const ::flatbuffers::String *new_owner_client_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NEW_OWNER_CLIENT_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DISPATCH_AREA_ID) &&
           verifier.VerifyString(dispatch_area_id()) &&
           VerifyOffsetRequired(verifier, VT_STATION_SID) &&
           verifier.VerifyString(station_sid()) &&
           VerifyOffset(verifier, VT_NEW_OWNER_CLIENT_ID) &&
           verifier.VerifyString(new_owner_client_id()) &&
           verifier.EndTable();
  }
  DispatchAreaOwnershipChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DispatchAreaOwnershipChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DispatchAreaOwnershipChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaOwnershipChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DispatchAreaOwnershipChangedBuilder {
  typedef DispatchAreaOwnershipChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dispatch_area_id(::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id) {
    fbb_.AddOffset(DispatchAreaOwnershipChanged::VT_DISPATCH_AREA_ID, dispatch_area_id);
  }
  void add_station_sid(::flatbuffers::Offset<::flatbuffers::String> station_sid) {
    fbb_.AddOffset(DispatchAreaOwnershipChanged::VT_STATION_SID, station_sid);
  }
  void add_new_owner_client_id(::flatbuffers::Offset<::flatbuffers::String> new_owner_client_id) {
    fbb_.AddOffset(DispatchAreaOwnershipChanged::VT_NEW_OWNER_CLIENT_ID, new_owner_client_id);
  }
  explicit DispatchAreaOwnershipChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DispatchAreaOwnershipChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DispatchAreaOwnershipChanged>(end);
    fbb_.Required(o, DispatchAreaOwnershipChanged::VT_DISPATCH_AREA_ID);
    fbb_.Required(o, DispatchAreaOwnershipChanged::VT_STATION_SID);
    return o;
  }
};

inline ::flatbuffers::Offset<DispatchAreaOwnershipChanged> CreateDispatchAreaOwnershipChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> station_sid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> new_owner_client_id = 0) {
  DispatchAreaOwnershipChangedBuilder builder_(_fbb);
  builder_.add_new_owner_client_id(new_owner_client_id);
  builder_.add_station_sid(station_sid);
  builder_.add_dispatch_area_id(dispatch_area_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DispatchAreaOwnershipChanged> CreateDispatchAreaOwnershipChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *dispatch_area_id = nullptr,
    const char *station_sid = nullptr,
    const char *new_owner_client_id = nullptr) {
  auto dispatch_area_id__ = dispatch_area_id ? _fbb.CreateString(dispatch_area_id) : 0;
  auto station_sid__ = station_sid ? _fbb.CreateString(station_sid) : 0;
  auto new_owner_client_id__ = new_owner_client_id ? _fbb.CreateString(new_owner_client_id) : 0;
  return proto::CreateDispatchAreaOwnershipChanged(
      _fbb,
      dispatch_area_id__,
      station_sid__,
      new_owner_client_id__);
}

::flatbuffers::Offset<DispatchAreaOwnershipChanged> CreateDispatchAreaOwnershipChanged(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaOwnershipChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SessionStateChangedT : public ::flatbuffers::NativeTable {
  typedef SessionStateChanged TableType;
  proto::SessionState new_state = proto::SessionState_STARTED;
};

struct SessionStateChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SessionStateChangedT NativeTableType;
  typedef SessionStateChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NEW_STATE = 4
  };
  proto::SessionState new_state() const {
    return static_cast<proto::SessionState>(GetField<int8_t>(VT_NEW_STATE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_NEW_STATE, 1) &&
           verifier.EndTable();
  }
  SessionStateChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SessionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SessionStateChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SessionStateChangedBuilder {
  typedef SessionStateChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_new_state(proto::SessionState new_state) {
    fbb_.AddElement<int8_t>(SessionStateChanged::VT_NEW_STATE, static_cast<int8_t>(new_state), 0);
  }
  explicit SessionStateChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SessionStateChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SessionStateChanged>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SessionStateChanged> CreateSessionStateChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    proto::SessionState new_state = proto::SessionState_STARTED) {
  SessionStateChangedBuilder builder_(_fbb);
  builder_.add_new_state(new_state);
  return builder_.Finish();
}

::flatbuffers::Offset<SessionStateChanged> CreateSessionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SessionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TrainComposedT : public ::flatbuffers::NativeTable {
  typedef TrainComposed TableType;
  std::string train_g_id{};
  std::vector<std::string> vehicle_g_ids{};
  float total_length_m = 0.0f;
  int32_t total_axles = 0;
};

struct TrainComposed FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainComposedT NativeTableType;
  typedef TrainComposedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRAIN_G_ID = 4,
    VT_VEHICLE_G_IDS = 6,
    VT_TOTAL_LENGTH_M = 8,
    VT_TOTAL_AXLES = 10
  };
  const ::flatbuffers::String *train_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_G_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *vehicle_g_ids() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_VEHICLE_G_IDS);
  }
  float total_length_m() const {
    return GetField<float>(VT_TOTAL_LENGTH_M, 0.0f);
  }
  int32_t total_axles() const {
    return GetField<int32_t>(VT_TOTAL_AXLES, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRAIN_G_ID) &&
           verifier.VerifyString(train_g_id()) &&
           VerifyOffset(verifier, VT_VEHICLE_G_IDS) &&
           verifier.VerifyVector(vehicle_g_ids()) &&
           verifier.VerifyVectorOfStrings(vehicle_g_ids()) &&
           VerifyField<float>(verifier, VT_TOTAL_LENGTH_M, 4) &&
           VerifyField<int32_t>(verifier, VT_TOTAL_AXLES, 4) &&
           verifier.EndTable();
  }
  TrainComposedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TrainComposedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TrainComposed> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainComposedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TrainComposedBuilder {
  typedef TrainComposed Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_train_g_id(::flatbuffers::Offset<::flatbuffers::String> train_g_id) {
    fbb_.AddOffset(TrainComposed::VT_TRAIN_G_ID, train_g_id);
  }
  void add_vehicle_g_ids(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> vehicle_g_ids) {
    fbb_.AddOffset(TrainComposed::VT_VEHICLE_G_IDS, vehicle_g_ids);
  }
  void add_total_length_m(float total_length_m) {
    fbb_.AddElement<float>(TrainComposed::VT_TOTAL_LENGTH_M, total_length_m, 0.0f);
  }
  void add_total_axles(int32_t total_axles) {
    fbb_.AddElement<int32_t>(TrainComposed::VT_TOTAL_AXLES, total_axles, 0);
  }
  explicit TrainComposedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainComposed> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainComposed>(end);
    fbb_.Required(o, TrainComposed::VT_TRAIN_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainComposed> CreateTrainComposed(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> train_g_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> vehicle_g_ids = 0,
    float total_length_m = 0.0f,
    int32_t total_axles = 0) {
  TrainComposedBuilder builder_(_fbb);
  builder_.add_total_axles(total_axles);
  builder_.add_total_length_m(total_length_m);
  builder_.add_vehicle_g_ids(vehicle_g_ids);
  builder_.add_train_g_id(train_g_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainComposed> CreateTrainComposedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *train_g_id = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *vehicle_g_ids = nullptr,
    float total_length_m = 0.0f,
    int32_t total_axles = 0) {
  auto train_g_id__ = train_g_id ? _fbb.CreateString(train_g_id) : 0;
  auto vehicle_g_ids__ = vehicle_g_ids ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*vehicle_g_ids) : 0;
  return proto::CreateTrainComposed(
      _fbb,
      train_g_id__,
      vehicle_g_ids__,
      total_length_m,
      total_axles);
}

::flatbuffers::Offset<TrainComposed> CreateTrainComposed(::flatbuffers::FlatBufferBuilder &_fbb, const TrainComposedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TrainDecomposedT : public ::flatbuffers::NativeTable {
  typedef TrainDecomposed TableType;
  std::string train_g_id{};
  proto::TrainDecomposeReason reason = proto::TrainDecomposeReason_UNCOUPLED;
};

struct TrainDecomposed FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrainDecomposedT NativeTableType;
  typedef TrainDecomposedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRAIN_G_ID = 4,
    VT_REASON = 6
  };
  const ::flatbuffers::String *train_g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRAIN_G_ID);
  }
  proto::TrainDecomposeReason reason() const {
    return static_cast<proto::TrainDecomposeReason>(GetField<int8_t>(VT_REASON, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TRAIN_G_ID) &&
           verifier.VerifyString(train_g_id()) &&
           VerifyField<int8_t>(verifier, VT_REASON, 1) &&
           verifier.EndTable();
  }
  TrainDecomposedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TrainDecomposedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TrainDecomposed> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainDecomposedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TrainDecomposedBuilder {
  typedef TrainDecomposed Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_train_g_id(::flatbuffers::Offset<::flatbuffers::String> train_g_id) {
    fbb_.AddOffset(TrainDecomposed::VT_TRAIN_G_ID, train_g_id);
  }
  void add_reason(proto::TrainDecomposeReason reason) {
    fbb_.AddElement<int8_t>(TrainDecomposed::VT_REASON, static_cast<int8_t>(reason), 0);
  }
  explicit TrainDecomposedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrainDecomposed> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrainDecomposed>(end);
    fbb_.Required(o, TrainDecomposed::VT_TRAIN_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<TrainDecomposed> CreateTrainDecomposed(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> train_g_id = 0,
    proto::TrainDecomposeReason reason = proto::TrainDecomposeReason_UNCOUPLED) {
  TrainDecomposedBuilder builder_(_fbb);
  builder_.add_train_g_id(train_g_id);
  builder_.add_reason(reason);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrainDecomposed> CreateTrainDecomposedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *train_g_id = nullptr,
    proto::TrainDecomposeReason reason = proto::TrainDecomposeReason_UNCOUPLED) {
  auto train_g_id__ = train_g_id ? _fbb.CreateString(train_g_id) : 0;
  return proto::CreateTrainDecomposed(
      _fbb,
      train_g_id__,
      reason);
}

::flatbuffers::Offset<TrainDecomposed> CreateTrainDecomposed(::flatbuffers::FlatBufferBuilder &_fbb, const TrainDecomposedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BlockDirectionStateChangedT : public ::flatbuffers::NativeTable {
  typedef BlockDirectionStateChanged TableType;
  std::string g_id{};
  proto::BlockDirectionState new_direction = proto::BlockDirectionState_NEUTRAL;
  proto::ChangeCause cause = proto::ChangeCause_COMMAND;
};

struct BlockDirectionStateChanged FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockDirectionStateChangedT NativeTableType;
  typedef BlockDirectionStateChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_G_ID = 4,
    VT_NEW_DIRECTION = 6,
    VT_CAUSE = 8
  };
  const ::flatbuffers::String *g_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_G_ID);
  }
  proto::BlockDirectionState new_direction() const {
    return static_cast<proto::BlockDirectionState>(GetField<int8_t>(VT_NEW_DIRECTION, 0));
  }
  proto::ChangeCause cause() const {
    return static_cast<proto::ChangeCause>(GetField<int8_t>(VT_CAUSE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_G_ID) &&
           verifier.VerifyString(g_id()) &&
           VerifyField<int8_t>(verifier, VT_NEW_DIRECTION, 1) &&
           VerifyField<int8_t>(verifier, VT_CAUSE, 1) &&
           verifier.EndTable();
  }
  BlockDirectionStateChangedT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlockDirectionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BlockDirectionStateChanged> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockDirectionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlockDirectionStateChangedBuilder {
  typedef BlockDirectionStateChanged Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_g_id(::flatbuffers::Offset<::flatbuffers::String> g_id) {
    fbb_.AddOffset(BlockDirectionStateChanged::VT_G_ID, g_id);
  }
  void add_new_direction(proto::BlockDirectionState new_direction) {
    fbb_.AddElement<int8_t>(BlockDirectionStateChanged::VT_NEW_DIRECTION, static_cast<int8_t>(new_direction), 0);
  }
  void add_cause(proto::ChangeCause cause) {
    fbb_.AddElement<int8_t>(BlockDirectionStateChanged::VT_CAUSE, static_cast<int8_t>(cause), 0);
  }
  explicit BlockDirectionStateChangedBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockDirectionStateChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockDirectionStateChanged>(end);
    fbb_.Required(o, BlockDirectionStateChanged::VT_G_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockDirectionStateChanged> CreateBlockDirectionStateChanged(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> g_id = 0,
    proto::BlockDirectionState new_direction = proto::BlockDirectionState_NEUTRAL,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  BlockDirectionStateChangedBuilder builder_(_fbb);
  builder_.add_g_id(g_id);
  builder_.add_cause(cause);
  builder_.add_new_direction(new_direction);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockDirectionStateChanged> CreateBlockDirectionStateChangedDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *g_id = nullptr,
    proto::BlockDirectionState new_direction = proto::BlockDirectionState_NEUTRAL,
    proto::ChangeCause cause = proto::ChangeCause_COMMAND) {
  auto g_id__ = g_id ? _fbb.CreateString(g_id) : 0;
  return proto::CreateBlockDirectionStateChanged(
      _fbb,
      g_id__,
      new_direction,
      cause);
}

::flatbuffers::Offset<BlockDirectionStateChanged> CreateBlockDirectionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const BlockDirectionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline SwitchPositionChangedT *SwitchPositionChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SwitchPositionChangedT>(new SwitchPositionChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SwitchPositionChanged::UnPackTo(SwitchPositionChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = new_position(); _o->new_position = _e; }
  { auto _e = cause(); _o->cause = _e; }
}

inline ::flatbuffers::Offset<SwitchPositionChanged> CreateSwitchPositionChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchPositionChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SwitchPositionChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SwitchPositionChanged> SwitchPositionChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchPositionChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SwitchPositionChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _new_position = _o->new_position;
  auto _cause = _o->cause;
  return proto::CreateSwitchPositionChanged(
      _fbb,
      _g_id,
      _new_position,
      _cause);
}

inline SwitchOccupancyChangedT *SwitchOccupancyChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SwitchOccupancyChangedT>(new SwitchOccupancyChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SwitchOccupancyChanged::UnPackTo(SwitchOccupancyChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = occupied(); _o->occupied = _e; }
  { auto _e = axle_count(); _o->axle_count = _e; }
  { auto _e = train_g_id(); if (_e) _o->train_g_id = _e->str(); }
}

inline ::flatbuffers::Offset<SwitchOccupancyChanged> CreateSwitchOccupancyChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchOccupancyChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SwitchOccupancyChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SwitchOccupancyChanged> SwitchOccupancyChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SwitchOccupancyChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SwitchOccupancyChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _occupied = _o->occupied;
  auto _axle_count = _o->axle_count;
  auto _train_g_id = _o->train_g_id.empty() ? 0 : _fbb.CreateString(_o->train_g_id);
  return proto::CreateSwitchOccupancyChanged(
      _fbb,
      _g_id,
      _occupied,
      _axle_count,
      _train_g_id);
}

inline SignalAspectChangedT *SignalAspectChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SignalAspectChangedT>(new SignalAspectChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SignalAspectChanged::UnPackTo(SignalAspectChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = new_aspect(); _o->new_aspect = _e; }
  { auto _e = cause(); _o->cause = _e; }
}

inline ::flatbuffers::Offset<SignalAspectChanged> CreateSignalAspectChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SignalAspectChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SignalAspectChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SignalAspectChanged> SignalAspectChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SignalAspectChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SignalAspectChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _new_aspect = _o->new_aspect;
  auto _cause = _o->cause;
  return proto::CreateSignalAspectChanged(
      _fbb,
      _g_id,
      _new_aspect,
      _cause);
}

inline TrackSectionOccupancyChangedT *TrackSectionOccupancyChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TrackSectionOccupancyChangedT>(new TrackSectionOccupancyChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TrackSectionOccupancyChanged::UnPackTo(TrackSectionOccupancyChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = occupied(); _o->occupied = _e; }
  { auto _e = axle_count(); _o->axle_count = _e; }
  { auto _e = train_g_id(); if (_e) _o->train_g_id = _e->str(); }
}

inline ::flatbuffers::Offset<TrackSectionOccupancyChanged> CreateTrackSectionOccupancyChanged(::flatbuffers::FlatBufferBuilder &_fbb, const TrackSectionOccupancyChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TrackSectionOccupancyChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TrackSectionOccupancyChanged> TrackSectionOccupancyChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrackSectionOccupancyChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TrackSectionOccupancyChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _occupied = _o->occupied;
  auto _axle_count = _o->axle_count;
  auto _train_g_id = _o->train_g_id.empty() ? 0 : _fbb.CreateString(_o->train_g_id);
  return proto::CreateTrackSectionOccupancyChanged(
      _fbb,
      _g_id,
      _occupied,
      _axle_count,
      _train_g_id);
}

inline DerailerPositionChangedT *DerailerPositionChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DerailerPositionChangedT>(new DerailerPositionChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DerailerPositionChanged::UnPackTo(DerailerPositionChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = new_position(); _o->new_position = _e; }
  { auto _e = cause(); _o->cause = _e; }
}

inline ::flatbuffers::Offset<DerailerPositionChanged> CreateDerailerPositionChanged(::flatbuffers::FlatBufferBuilder &_fbb, const DerailerPositionChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DerailerPositionChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DerailerPositionChanged> DerailerPositionChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DerailerPositionChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DerailerPositionChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _new_position = _o->new_position;
  auto _cause = _o->cause;
  return proto::CreateDerailerPositionChanged(
      _fbb,
      _g_id,
      _new_position,
      _cause);
}

inline BlockSectionStateChangedT *BlockSectionStateChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockSectionStateChangedT>(new BlockSectionStateChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockSectionStateChanged::UnPackTo(BlockSectionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = new_state(); _o->new_state = _e; }
}

inline ::flatbuffers::Offset<BlockSectionStateChanged> CreateBlockSectionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const BlockSectionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return BlockSectionStateChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockSectionStateChanged> BlockSectionStateChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockSectionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockSectionStateChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _new_state = _o->new_state;
  return proto::CreateBlockSectionStateChanged(
      _fbb,
      _g_id,
      _new_state);
}

inline RouteSetT *RouteSet::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RouteSetT>(new RouteSetT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RouteSet::UnPackTo(RouteSetT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = route_id(); if (_e) _o->route_id = _e->str(); }
  { auto _e = from_g_id(); if (_e) _o->from_g_id = _e->str(); }
  { auto _e = to_g_id(); if (_e) _o->to_g_id = _e->str(); }
  { auto _e = section_ids(); if (_e) { _o->section_ids.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->section_ids[_i] = _e->Get(_i)->str(); } } else { _o->section_ids.resize(0); } }
}

inline ::flatbuffers::Offset<RouteSet> CreateRouteSet(::flatbuffers::FlatBufferBuilder &_fbb, const RouteSetT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return RouteSet::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RouteSet> RouteSet::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RouteSetT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RouteSetT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _route_id = _fbb.CreateString(_o->route_id);
  auto _from_g_id = _fbb.CreateString(_o->from_g_id);
  auto _to_g_id = _fbb.CreateString(_o->to_g_id);
  auto _section_ids = _o->section_ids.size() ? _fbb.CreateVectorOfStrings(_o->section_ids) : 0;
  return proto::CreateRouteSet(
      _fbb,
      _route_id,
      _from_g_id,
      _to_g_id,
      _section_ids);
}

inline RouteReleasedT *RouteReleased::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RouteReleasedT>(new RouteReleasedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RouteReleased::UnPackTo(RouteReleasedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = route_id(); if (_e) _o->route_id = _e->str(); }
  { auto _e = reason(); _o->reason = _e; }
}

inline ::flatbuffers::Offset<RouteReleased> CreateRouteReleased(::flatbuffers::FlatBufferBuilder &_fbb, const RouteReleasedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return RouteReleased::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RouteReleased> RouteReleased::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RouteReleasedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RouteReleasedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _route_id = _fbb.CreateString(_o->route_id);
  auto _reason = _o->reason;
  return proto::CreateRouteReleased(
      _fbb,
      _route_id,
      _reason);
}

inline TrainMovementT *TrainMovement::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TrainMovementT>(new TrainMovementT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TrainMovement::UnPackTo(TrainMovementT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = train_g_id(); if (_e) _o->train_g_id = _e->str(); }
  { auto _e = section_g_id(); if (_e) _o->section_g_id = _e->str(); }
  { auto _e = direction(); _o->direction = _e; }
  { auto _e = speed_kmh(); _o->speed_kmh = _e; }
}

inline ::flatbuffers::Offset<TrainMovement> CreateTrainMovement(::flatbuffers::FlatBufferBuilder &_fbb, const TrainMovementT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TrainMovement::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TrainMovement> TrainMovement::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainMovementT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TrainMovementT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _train_g_id = _fbb.CreateString(_o->train_g_id);
  auto _section_g_id = _fbb.CreateString(_o->section_g_id);
  auto _direction = _o->direction;
  auto _speed_kmh = _o->speed_kmh;
  return proto::CreateTrainMovement(
      _fbb,
      _train_g_id,
      _section_g_id,
      _direction,
      _speed_kmh);
}

inline AlarmRaisedT *AlarmRaised::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AlarmRaisedT>(new AlarmRaisedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AlarmRaised::UnPackTo(AlarmRaisedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = alarm_id(); if (_e) _o->alarm_id = _e->str(); }
  { auto _e = alarm_type(); _o->alarm_type = _e; }
  { auto _e = object_g_id(); if (_e) _o->object_g_id = _e->str(); }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline ::flatbuffers::Offset<AlarmRaised> CreateAlarmRaised(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmRaisedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return AlarmRaised::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AlarmRaised> AlarmRaised::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmRaisedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AlarmRaisedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _alarm_id = _fbb.CreateString(_o->alarm_id);
  auto _alarm_type = _o->alarm_type;
  auto _object_g_id = _o->object_g_id.empty() ? 0 : _fbb.CreateString(_o->object_g_id);
  auto _message = _o->message.empty() ? 0 : _fbb.CreateString(_o->message);
  return proto::CreateAlarmRaised(
      _fbb,
      _alarm_id,
      _alarm_type,
      _object_g_id,
      _message);
}

inline AlarmClearedT *AlarmCleared::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AlarmClearedT>(new AlarmClearedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AlarmCleared::UnPackTo(AlarmClearedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = alarm_id(); if (_e) _o->alarm_id = _e->str(); }
}

inline ::flatbuffers::Offset<AlarmCleared> CreateAlarmCleared(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmClearedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return AlarmCleared::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AlarmCleared> AlarmCleared::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AlarmClearedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AlarmClearedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _alarm_id = _fbb.CreateString(_o->alarm_id);
  return proto::CreateAlarmCleared(
      _fbb,
      _alarm_id);
}

inline DispatchAreaOwnershipChangedT *DispatchAreaOwnershipChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DispatchAreaOwnershipChangedT>(new DispatchAreaOwnershipChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DispatchAreaOwnershipChanged::UnPackTo(DispatchAreaOwnershipChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dispatch_area_id(); if (_e) _o->dispatch_area_id = _e->str(); }
  { auto _e = station_sid(); if (_e) _o->station_sid = _e->str(); }
  { auto _e = new_owner_client_id(); if (_e) _o->new_owner_client_id = _e->str(); }
}

inline ::flatbuffers::Offset<DispatchAreaOwnershipChanged> CreateDispatchAreaOwnershipChanged(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaOwnershipChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DispatchAreaOwnershipChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DispatchAreaOwnershipChanged> DispatchAreaOwnershipChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaOwnershipChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DispatchAreaOwnershipChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dispatch_area_id = _fbb.CreateString(_o->dispatch_area_id);
  auto _station_sid = _fbb.CreateString(_o->station_sid);
  auto _new_owner_client_id = _o->new_owner_client_id.empty() ? 0 : _fbb.CreateString(_o->new_owner_client_id);
  return proto::CreateDispatchAreaOwnershipChanged(
      _fbb,
      _dispatch_area_id,
      _station_sid,
      _new_owner_client_id);
}

inline SessionStateChangedT *SessionStateChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SessionStateChangedT>(new SessionStateChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SessionStateChanged::UnPackTo(SessionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = new_state(); _o->new_state = _e; }
}

inline ::flatbuffers::Offset<SessionStateChanged> CreateSessionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const SessionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SessionStateChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SessionStateChanged> SessionStateChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SessionStateChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _new_state = _o->new_state;
  return proto::CreateSessionStateChanged(
      _fbb,
      _new_state);
}

inline TrainComposedT *TrainComposed::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TrainComposedT>(new TrainComposedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TrainComposed::UnPackTo(TrainComposedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = train_g_id(); if (_e) _o->train_g_id = _e->str(); }
  { auto _e = vehicle_g_ids(); if (_e) { _o->vehicle_g_ids.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->vehicle_g_ids[_i] = _e->Get(_i)->str(); } } else { _o->vehicle_g_ids.resize(0); } }
  { auto _e = total_length_m(); _o->total_length_m = _e; }
  { auto _e = total_axles(); _o->total_axles = _e; }
}

inline ::flatbuffers::Offset<TrainComposed> CreateTrainComposed(::flatbuffers::FlatBufferBuilder &_fbb, const TrainComposedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TrainComposed::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TrainComposed> TrainComposed::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainComposedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TrainComposedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _train_g_id = _fbb.CreateString(_o->train_g_id);
  auto _vehicle_g_ids = _o->vehicle_g_ids.size() ? _fbb.CreateVectorOfStrings(_o->vehicle_g_ids) : 0;
  auto _total_length_m = _o->total_length_m;
  auto _total_axles = _o->total_axles;
  return proto::CreateTrainComposed(
      _fbb,
      _train_g_id,
      _vehicle_g_ids,
      _total_length_m,
      _total_axles);
}

inline TrainDecomposedT *TrainDecomposed::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TrainDecomposedT>(new TrainDecomposedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TrainDecomposed::UnPackTo(TrainDecomposedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = train_g_id(); if (_e) _o->train_g_id = _e->str(); }
  { auto _e = reason(); _o->reason = _e; }
}

inline ::flatbuffers::Offset<TrainDecomposed> CreateTrainDecomposed(::flatbuffers::FlatBufferBuilder &_fbb, const TrainDecomposedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TrainDecomposed::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TrainDecomposed> TrainDecomposed::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TrainDecomposedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TrainDecomposedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _train_g_id = _fbb.CreateString(_o->train_g_id);
  auto _reason = _o->reason;
  return proto::CreateTrainDecomposed(
      _fbb,
      _train_g_id,
      _reason);
}

inline BlockDirectionStateChangedT *BlockDirectionStateChanged::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlockDirectionStateChangedT>(new BlockDirectionStateChangedT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BlockDirectionStateChanged::UnPackTo(BlockDirectionStateChangedT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = g_id(); if (_e) _o->g_id = _e->str(); }
  { auto _e = new_direction(); _o->new_direction = _e; }
  { auto _e = cause(); _o->cause = _e; }
}

inline ::flatbuffers::Offset<BlockDirectionStateChanged> CreateBlockDirectionStateChanged(::flatbuffers::FlatBufferBuilder &_fbb, const BlockDirectionStateChangedT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return BlockDirectionStateChanged::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BlockDirectionStateChanged> BlockDirectionStateChanged::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlockDirectionStateChangedT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlockDirectionStateChangedT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _g_id = _fbb.CreateString(_o->g_id);
  auto _new_direction = _o->new_direction;
  auto _cause = _o->cause;
  return proto::CreateBlockDirectionStateChanged(
      _fbb,
      _g_id,
      _new_direction,
      _cause);
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_EVENTS_PROTO_H_
