// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_OWNERSHIP_PROTO_H_
#define FLATBUFFERS_GENERATED_OWNERSHIP_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 && FLATBUFFERS_VERSION_MINOR == 12 &&
                  FLATBUFFERS_VERSION_REVISION == 19,
              "Non-compatible flatbuffers version included");

namespace proto
{

struct TakeoverRequest;
struct TakeoverRequestBuilder;
struct TakeoverRequestT;

struct TakeoverResponse;
struct TakeoverResponseBuilder;
struct TakeoverResponseT;

struct TakeoverRequestT : public ::flatbuffers::NativeTable
{
    typedef TakeoverRequest TableType;
    std::string dispatch_area_id{};
    std::string station_sid{};
    bool release = false;
    std::string reason_text{};
};

/// C → S  (msg_type 0x50)
struct TakeoverRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table
{
    typedef TakeoverRequestT NativeTableType;
    typedef TakeoverRequestBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE
    {
        VT_DISPATCH_AREA_ID = 4,
        VT_STATION_SID = 6,
        VT_RELEASE = 8,
        VT_REASON_TEXT = 10
    };
    const ::flatbuffers::String *dispatch_area_id() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_DISPATCH_AREA_ID);
    }
    const ::flatbuffers::String *station_sid() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_STATION_SID);
    }
    /// True means release ownership instead of acquire.
    bool release() const { return GetField<uint8_t>(VT_RELEASE, 0) != 0; }
    /// Optional human-readable reason (audit/logging).
    const ::flatbuffers::String *reason_text() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_REASON_TEXT);
    }
    template<bool B = false>
    bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const
    {
        return VerifyTableStart(verifier) && VerifyOffsetRequired(verifier, VT_DISPATCH_AREA_ID) &&
               verifier.VerifyString(dispatch_area_id()) &&
               VerifyOffsetRequired(verifier, VT_STATION_SID) &&
               verifier.VerifyString(station_sid()) &&
               VerifyField<uint8_t>(verifier, VT_RELEASE, 1) &&
               VerifyOffset(verifier, VT_REASON_TEXT) && verifier.VerifyString(reason_text()) &&
               verifier.EndTable();
    }
    TakeoverRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    void UnPackTo(TakeoverRequestT *_o,
                  const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    static ::flatbuffers::Offset<TakeoverRequest> Pack(
        ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverRequestT *_o,
        const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TakeoverRequestBuilder
{
    typedef TakeoverRequest Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_dispatch_area_id(::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id)
    {
        fbb_.AddOffset(TakeoverRequest::VT_DISPATCH_AREA_ID, dispatch_area_id);
    }
    void add_station_sid(::flatbuffers::Offset<::flatbuffers::String> station_sid)
    {
        fbb_.AddOffset(TakeoverRequest::VT_STATION_SID, station_sid);
    }
    void add_release(bool release)
    {
        fbb_.AddElement<uint8_t>(TakeoverRequest::VT_RELEASE, static_cast<uint8_t>(release), 0);
    }
    void add_reason_text(::flatbuffers::Offset<::flatbuffers::String> reason_text)
    {
        fbb_.AddOffset(TakeoverRequest::VT_REASON_TEXT, reason_text);
    }
    explicit TakeoverRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<TakeoverRequest> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<TakeoverRequest>(end);
        fbb_.Required(o, TakeoverRequest::VT_DISPATCH_AREA_ID);
        fbb_.Required(o, TakeoverRequest::VT_STATION_SID);
        return o;
    }
};

inline ::flatbuffers::Offset<TakeoverRequest> CreateTakeoverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> station_sid = 0, bool release = false,
    ::flatbuffers::Offset<::flatbuffers::String> reason_text = 0)
{
    TakeoverRequestBuilder builder_(_fbb);
    builder_.add_reason_text(reason_text);
    builder_.add_station_sid(station_sid);
    builder_.add_dispatch_area_id(dispatch_area_id);
    builder_.add_release(release);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<TakeoverRequest> CreateTakeoverRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, const char *dispatch_area_id = nullptr,
    const char *station_sid = nullptr, bool release = false, const char *reason_text = nullptr)
{
    auto dispatch_area_id__ = dispatch_area_id ? _fbb.CreateString(dispatch_area_id) : 0;
    auto station_sid__ = station_sid ? _fbb.CreateString(station_sid) : 0;
    auto reason_text__ = reason_text ? _fbb.CreateString(reason_text) : 0;
    return proto::CreateTakeoverRequest(_fbb, dispatch_area_id__, station_sid__, release,
                                        reason_text__);
}

::flatbuffers::Offset<TakeoverRequest> CreateTakeoverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverRequestT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TakeoverResponseT : public ::flatbuffers::NativeTable
{
    typedef TakeoverResponse TableType;
    bool granted = false;
    std::string dispatch_area_id{};
    std::string station_sid{};
    std::string reject_reason{};
};

/// S → C  (msg_type 0x51)
struct TakeoverResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table
{
    typedef TakeoverResponseT NativeTableType;
    typedef TakeoverResponseBuilder Builder;
    enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE
    {
        VT_GRANTED = 4,
        VT_DISPATCH_AREA_ID = 6,
        VT_STATION_SID = 8,
        VT_REJECT_REASON = 10
    };
    bool granted() const { return GetField<uint8_t>(VT_GRANTED, 0) != 0; }
    const ::flatbuffers::String *dispatch_area_id() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_DISPATCH_AREA_ID);
    }
    const ::flatbuffers::String *station_sid() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_STATION_SID);
    }
    /// Present only when granted=false.
    const ::flatbuffers::String *reject_reason() const
    {
        return GetPointer<const ::flatbuffers::String *>(VT_REJECT_REASON);
    }
    template<bool B = false>
    bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const
    {
        return VerifyTableStart(verifier) && VerifyField<uint8_t>(verifier, VT_GRANTED, 1) &&
               VerifyOffsetRequired(verifier, VT_DISPATCH_AREA_ID) &&
               verifier.VerifyString(dispatch_area_id()) &&
               VerifyOffsetRequired(verifier, VT_STATION_SID) &&
               verifier.VerifyString(station_sid()) && VerifyOffset(verifier, VT_REJECT_REASON) &&
               verifier.VerifyString(reject_reason()) && verifier.EndTable();
    }
    TakeoverResponseT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    void UnPackTo(TakeoverResponseT *_o,
                  const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
    static ::flatbuffers::Offset<TakeoverResponse> Pack(
        ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverResponseT *_o,
        const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TakeoverResponseBuilder
{
    typedef TakeoverResponse Table;
    ::flatbuffers::FlatBufferBuilder &fbb_;
    ::flatbuffers::uoffset_t start_;
    void add_granted(bool granted)
    {
        fbb_.AddElement<uint8_t>(TakeoverResponse::VT_GRANTED, static_cast<uint8_t>(granted), 0);
    }
    void add_dispatch_area_id(::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id)
    {
        fbb_.AddOffset(TakeoverResponse::VT_DISPATCH_AREA_ID, dispatch_area_id);
    }
    void add_station_sid(::flatbuffers::Offset<::flatbuffers::String> station_sid)
    {
        fbb_.AddOffset(TakeoverResponse::VT_STATION_SID, station_sid);
    }
    void add_reject_reason(::flatbuffers::Offset<::flatbuffers::String> reject_reason)
    {
        fbb_.AddOffset(TakeoverResponse::VT_REJECT_REASON, reject_reason);
    }
    explicit TakeoverResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb)
    {
        start_ = fbb_.StartTable();
    }
    ::flatbuffers::Offset<TakeoverResponse> Finish()
    {
        const auto end = fbb_.EndTable(start_);
        auto o = ::flatbuffers::Offset<TakeoverResponse>(end);
        fbb_.Required(o, TakeoverResponse::VT_DISPATCH_AREA_ID);
        fbb_.Required(o, TakeoverResponse::VT_STATION_SID);
        return o;
    }
};

inline ::flatbuffers::Offset<TakeoverResponse> CreateTakeoverResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb, bool granted = false,
    ::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> station_sid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> reject_reason = 0)
{
    TakeoverResponseBuilder builder_(_fbb);
    builder_.add_reject_reason(reject_reason);
    builder_.add_station_sid(station_sid);
    builder_.add_dispatch_area_id(dispatch_area_id);
    builder_.add_granted(granted);
    return builder_.Finish();
}

inline ::flatbuffers::Offset<TakeoverResponse> CreateTakeoverResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb, bool granted = false,
    const char *dispatch_area_id = nullptr, const char *station_sid = nullptr,
    const char *reject_reason = nullptr)
{
    auto dispatch_area_id__ = dispatch_area_id ? _fbb.CreateString(dispatch_area_id) : 0;
    auto station_sid__ = station_sid ? _fbb.CreateString(station_sid) : 0;
    auto reject_reason__ = reject_reason ? _fbb.CreateString(reject_reason) : 0;
    return proto::CreateTakeoverResponse(_fbb, granted, dispatch_area_id__, station_sid__,
                                         reject_reason__);
}

::flatbuffers::Offset<TakeoverResponse> CreateTakeoverResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverResponseT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TakeoverRequestT *TakeoverRequest::UnPack(
    const ::flatbuffers::resolver_function_t *_resolver) const
{
    auto _o = std::unique_ptr<TakeoverRequestT>(new TakeoverRequestT());
    UnPackTo(_o.get(), _resolver);
    return _o.release();
}

inline void TakeoverRequest::UnPackTo(TakeoverRequestT *_o,
                                      const ::flatbuffers::resolver_function_t *_resolver) const
{
    (void)_o;
    (void)_resolver;
    {
        auto _e = dispatch_area_id();
        if (_e)
            _o->dispatch_area_id = _e->str();
    }
    {
        auto _e = station_sid();
        if (_e)
            _o->station_sid = _e->str();
    }
    {
        auto _e = release();
        _o->release = _e;
    }
    {
        auto _e = reason_text();
        if (_e)
            _o->reason_text = _e->str();
    }
}

inline ::flatbuffers::Offset<TakeoverRequest> CreateTakeoverRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverRequestT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    return TakeoverRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TakeoverRequest> TakeoverRequest::Pack(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverRequestT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    (void)_rehasher;
    (void)_o;
    struct _VectorArgs
    {
        ::flatbuffers::FlatBufferBuilder *__fbb;
        const TakeoverRequestT *__o;
        const ::flatbuffers::rehasher_function_t *__rehasher;
    } _va = {&_fbb, _o, _rehasher};
    (void)_va;
    auto _dispatch_area_id = _fbb.CreateString(_o->dispatch_area_id);
    auto _station_sid = _fbb.CreateString(_o->station_sid);
    auto _release = _o->release;
    auto _reason_text = _o->reason_text.empty() ? 0 : _fbb.CreateString(_o->reason_text);
    return proto::CreateTakeoverRequest(_fbb, _dispatch_area_id, _station_sid, _release,
                                        _reason_text);
}

inline TakeoverResponseT *TakeoverResponse::UnPack(
    const ::flatbuffers::resolver_function_t *_resolver) const
{
    auto _o = std::unique_ptr<TakeoverResponseT>(new TakeoverResponseT());
    UnPackTo(_o.get(), _resolver);
    return _o.release();
}

inline void TakeoverResponse::UnPackTo(TakeoverResponseT *_o,
                                       const ::flatbuffers::resolver_function_t *_resolver) const
{
    (void)_o;
    (void)_resolver;
    {
        auto _e = granted();
        _o->granted = _e;
    }
    {
        auto _e = dispatch_area_id();
        if (_e)
            _o->dispatch_area_id = _e->str();
    }
    {
        auto _e = station_sid();
        if (_e)
            _o->station_sid = _e->str();
    }
    {
        auto _e = reject_reason();
        if (_e)
            _o->reject_reason = _e->str();
    }
}

inline ::flatbuffers::Offset<TakeoverResponse> CreateTakeoverResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverResponseT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    return TakeoverResponse::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TakeoverResponse> TakeoverResponse::Pack(
    ::flatbuffers::FlatBufferBuilder &_fbb, const TakeoverResponseT *_o,
    const ::flatbuffers::rehasher_function_t *_rehasher)
{
    (void)_rehasher;
    (void)_o;
    struct _VectorArgs
    {
        ::flatbuffers::FlatBufferBuilder *__fbb;
        const TakeoverResponseT *__o;
        const ::flatbuffers::rehasher_function_t *__rehasher;
    } _va = {&_fbb, _o, _rehasher};
    (void)_va;
    auto _granted = _o->granted;
    auto _dispatch_area_id = _fbb.CreateString(_o->dispatch_area_id);
    auto _station_sid = _fbb.CreateString(_o->station_sid);
    auto _reject_reason = _o->reject_reason.empty() ? 0 : _fbb.CreateString(_o->reject_reason);
    return proto::CreateTakeoverResponse(_fbb, _granted, _dispatch_area_id, _station_sid,
                                         _reject_reason);
}

inline const proto::TakeoverResponse *GetTakeoverResponse(const void *buf)
{
    return ::flatbuffers::GetRoot<proto::TakeoverResponse>(buf);
}

inline const proto::TakeoverResponse *GetSizePrefixedTakeoverResponse(const void *buf)
{
    return ::flatbuffers::GetSizePrefixedRoot<proto::TakeoverResponse>(buf);
}

template<bool B = false>
inline bool VerifyTakeoverResponseBuffer(::flatbuffers::VerifierTemplate<B> &verifier)
{
    return verifier.template VerifyBuffer<proto::TakeoverResponse>(nullptr);
}

template<bool B = false>
inline bool VerifySizePrefixedTakeoverResponseBuffer(::flatbuffers::VerifierTemplate<B> &verifier)
{
    return verifier.template VerifySizePrefixedBuffer<proto::TakeoverResponse>(nullptr);
}

inline void FinishTakeoverResponseBuffer(::flatbuffers::FlatBufferBuilder &fbb,
                                         ::flatbuffers::Offset<proto::TakeoverResponse> root)
{
    fbb.Finish(root);
}

inline void FinishSizePrefixedTakeoverResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb, ::flatbuffers::Offset<proto::TakeoverResponse> root)
{
    fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::TakeoverResponseT> UnPackTakeoverResponse(
    const void *buf, const ::flatbuffers::resolver_function_t *res = nullptr)
{
    return std::unique_ptr<proto::TakeoverResponseT>(GetTakeoverResponse(buf)->UnPack(res));
}

inline std::unique_ptr<proto::TakeoverResponseT> UnPackSizePrefixedTakeoverResponse(
    const void *buf, const ::flatbuffers::resolver_function_t *res = nullptr)
{
    return std::unique_ptr<proto::TakeoverResponseT>(
        GetSizePrefixedTakeoverResponse(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_OWNERSHIP_PROTO_H_
