// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SESSION_PROTO_H_
#define FLATBUFFERS_GENERATED_SESSION_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common_generated.h"

namespace proto {

struct DispatchAreaInfo;
struct DispatchAreaInfoBuilder;
struct DispatchAreaInfoT;

struct Handshake;
struct HandshakeBuilder;
struct HandshakeT;

struct HandshakeAck;
struct HandshakeAckBuilder;
struct HandshakeAckT;

struct Heartbeat;
struct HeartbeatBuilder;
struct HeartbeatT;

struct HeartbeatAck;
struct HeartbeatAckBuilder;
struct HeartbeatAckT;

struct SnapshotRequest;
struct SnapshotRequestBuilder;
struct SnapshotRequestT;

struct SessionNotice;
struct SessionNoticeBuilder;
struct SessionNoticeT;

enum SessionNoticeType : int8_t {
  SessionNoticeType_INFO = 0,
  SessionNoticeType_WARNING = 1,
  SessionNoticeType_ERROR = 2,
  SessionNoticeType_STATE_CHANGE = 3,
  SessionNoticeType_OWNERSHIP_REVOKED = 4,
  SessionNoticeType_MIN = SessionNoticeType_INFO,
  SessionNoticeType_MAX = SessionNoticeType_OWNERSHIP_REVOKED
};

inline const SessionNoticeType (&EnumValuesSessionNoticeType())[5] {
  static const SessionNoticeType values[] = {
    SessionNoticeType_INFO,
    SessionNoticeType_WARNING,
    SessionNoticeType_ERROR,
    SessionNoticeType_STATE_CHANGE,
    SessionNoticeType_OWNERSHIP_REVOKED
  };
  return values;
}

inline const char * const *EnumNamesSessionNoticeType() {
  static const char * const names[6] = {
    "INFO",
    "WARNING",
    "ERROR",
    "STATE_CHANGE",
    "OWNERSHIP_REVOKED",
    nullptr
  };
  return names;
}

inline const char *EnumNameSessionNoticeType(SessionNoticeType e) {
  if (::flatbuffers::IsOutRange(e, SessionNoticeType_INFO, SessionNoticeType_OWNERSHIP_REVOKED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSessionNoticeType()[index];
}

struct DispatchAreaInfoT : public ::flatbuffers::NativeTable {
  typedef DispatchAreaInfo TableType;
  std::string dispatch_area_id{};
  std::string station_sid{};
  std::string display_name{};
};

/// Scope of objects (switches, signals) that belong to one dispatch area (sub-post).
struct DispatchAreaInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DispatchAreaInfoT NativeTableType;
  typedef DispatchAreaInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DISPATCH_AREA_ID = 4,
    VT_STATION_SID = 6,
    VT_DISPLAY_NAME = 8
  };
  const ::flatbuffers::String *dispatch_area_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPATCH_AREA_ID);
  }
  const ::flatbuffers::String *station_sid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATION_SID);
  }
  const ::flatbuffers::String *display_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPLAY_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_DISPATCH_AREA_ID) &&
           verifier.VerifyString(dispatch_area_id()) &&
           VerifyOffsetRequired(verifier, VT_STATION_SID) &&
           verifier.VerifyString(station_sid()) &&
           VerifyOffset(verifier, VT_DISPLAY_NAME) &&
           verifier.VerifyString(display_name()) &&
           verifier.EndTable();
  }
  DispatchAreaInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DispatchAreaInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DispatchAreaInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DispatchAreaInfoBuilder {
  typedef DispatchAreaInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dispatch_area_id(::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id) {
    fbb_.AddOffset(DispatchAreaInfo::VT_DISPATCH_AREA_ID, dispatch_area_id);
  }
  void add_station_sid(::flatbuffers::Offset<::flatbuffers::String> station_sid) {
    fbb_.AddOffset(DispatchAreaInfo::VT_STATION_SID, station_sid);
  }
  void add_display_name(::flatbuffers::Offset<::flatbuffers::String> display_name) {
    fbb_.AddOffset(DispatchAreaInfo::VT_DISPLAY_NAME, display_name);
  }
  explicit DispatchAreaInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DispatchAreaInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DispatchAreaInfo>(end);
    fbb_.Required(o, DispatchAreaInfo::VT_DISPATCH_AREA_ID);
    fbb_.Required(o, DispatchAreaInfo::VT_STATION_SID);
    return o;
  }
};

inline ::flatbuffers::Offset<DispatchAreaInfo> CreateDispatchAreaInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> station_sid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> display_name = 0) {
  DispatchAreaInfoBuilder builder_(_fbb);
  builder_.add_display_name(display_name);
  builder_.add_station_sid(station_sid);
  builder_.add_dispatch_area_id(dispatch_area_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DispatchAreaInfo> CreateDispatchAreaInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *dispatch_area_id = nullptr,
    const char *station_sid = nullptr,
    const char *display_name = nullptr) {
  auto dispatch_area_id__ = dispatch_area_id ? _fbb.CreateString(dispatch_area_id) : 0;
  auto station_sid__ = station_sid ? _fbb.CreateString(station_sid) : 0;
  auto display_name__ = display_name ? _fbb.CreateString(display_name) : 0;
  return proto::CreateDispatchAreaInfo(
      _fbb,
      dispatch_area_id__,
      station_sid__,
      display_name__);
}

::flatbuffers::Offset<DispatchAreaInfo> CreateDispatchAreaInfo(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HandshakeT : public ::flatbuffers::NativeTable {
  typedef Handshake TableType;
  uint32_t proto_version = 0;
  std::string player_id{};
  std::string auth_token{};
  std::string client_version{};
};

/// C → S  (msg_type 0x01)
struct Handshake FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandshakeT NativeTableType;
  typedef HandshakeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PROTO_VERSION = 4,
    VT_PLAYER_ID = 6,
    VT_AUTH_TOKEN = 8,
    VT_CLIENT_VERSION = 10
  };
  /// Protocol version — must match server's supported version.
  uint32_t proto_version() const {
    return GetField<uint32_t>(VT_PROTO_VERSION, 0);
  }
  /// Player identifier from the game-management system.
  const ::flatbuffers::String *player_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PLAYER_ID);
  }
  /// Bearer token issued by the auth service (HMAC-SHA256 signed JWT).
  const ::flatbuffers::String *auth_token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTH_TOKEN);
  }
  /// Human-readable client version string for diagnostics.
  const ::flatbuffers::String *client_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CLIENT_VERSION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PROTO_VERSION, 4) &&
           VerifyOffsetRequired(verifier, VT_PLAYER_ID) &&
           verifier.VerifyString(player_id()) &&
           VerifyOffsetRequired(verifier, VT_AUTH_TOKEN) &&
           verifier.VerifyString(auth_token()) &&
           VerifyOffset(verifier, VT_CLIENT_VERSION) &&
           verifier.VerifyString(client_version()) &&
           verifier.EndTable();
  }
  HandshakeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HandshakeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Handshake> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HandshakeBuilder {
  typedef Handshake Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_proto_version(uint32_t proto_version) {
    fbb_.AddElement<uint32_t>(Handshake::VT_PROTO_VERSION, proto_version, 0);
  }
  void add_player_id(::flatbuffers::Offset<::flatbuffers::String> player_id) {
    fbb_.AddOffset(Handshake::VT_PLAYER_ID, player_id);
  }
  void add_auth_token(::flatbuffers::Offset<::flatbuffers::String> auth_token) {
    fbb_.AddOffset(Handshake::VT_AUTH_TOKEN, auth_token);
  }
  void add_client_version(::flatbuffers::Offset<::flatbuffers::String> client_version) {
    fbb_.AddOffset(Handshake::VT_CLIENT_VERSION, client_version);
  }
  explicit HandshakeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Handshake> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Handshake>(end);
    fbb_.Required(o, Handshake::VT_PLAYER_ID);
    fbb_.Required(o, Handshake::VT_AUTH_TOKEN);
    return o;
  }
};

inline ::flatbuffers::Offset<Handshake> CreateHandshake(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t proto_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> player_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> auth_token = 0,
    ::flatbuffers::Offset<::flatbuffers::String> client_version = 0) {
  HandshakeBuilder builder_(_fbb);
  builder_.add_client_version(client_version);
  builder_.add_auth_token(auth_token);
  builder_.add_player_id(player_id);
  builder_.add_proto_version(proto_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Handshake> CreateHandshakeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t proto_version = 0,
    const char *player_id = nullptr,
    const char *auth_token = nullptr,
    const char *client_version = nullptr) {
  auto player_id__ = player_id ? _fbb.CreateString(player_id) : 0;
  auto auth_token__ = auth_token ? _fbb.CreateString(auth_token) : 0;
  auto client_version__ = client_version ? _fbb.CreateString(client_version) : 0;
  return proto::CreateHandshake(
      _fbb,
      proto_version,
      player_id__,
      auth_token__,
      client_version__);
}

::flatbuffers::Offset<Handshake> CreateHandshake(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HandshakeAckT : public ::flatbuffers::NativeTable {
  typedef HandshakeAck TableType;
  std::string session_id{};
  uint32_t server_tick_hz = 20;
  std::vector<std::unique_ptr<proto::DispatchAreaInfoT>> assigned_dispatch_areas{};
  uint64_t server_time_us = 0;
  HandshakeAckT() = default;
  HandshakeAckT(const HandshakeAckT &o);
  HandshakeAckT(HandshakeAckT&&) FLATBUFFERS_NOEXCEPT = default;
  HandshakeAckT &operator=(HandshakeAckT o) FLATBUFFERS_NOEXCEPT;
};

/// S → C  (msg_type 0x02)
struct HandshakeAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HandshakeAckT NativeTableType;
  typedef HandshakeAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSION_ID = 4,
    VT_SERVER_TICK_HZ = 6,
    VT_ASSIGNED_DISPATCH_AREAS = 8,
    VT_SERVER_TIME_US = 10
  };
  /// Unique identifier for this simulation session.
  const ::flatbuffers::String *session_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SESSION_ID);
  }
  /// Tick rate of the simulation engine in Hz (default: 20).
  uint32_t server_tick_hz() const {
    return GetField<uint32_t>(VT_SERVER_TICK_HZ, 20);
  }
  /// List of dispatch areas this client is authorised to command.
  const ::flatbuffers::Vector<::flatbuffers::Offset<proto::DispatchAreaInfo>> *assigned_dispatch_areas() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<proto::DispatchAreaInfo>> *>(VT_ASSIGNED_DISPATCH_AREAS);
  }
  /// Current wall-clock time at session start, microseconds since Unix epoch.
  uint64_t server_time_us() const {
    return GetField<uint64_t>(VT_SERVER_TIME_US, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SESSION_ID) &&
           verifier.VerifyString(session_id()) &&
           VerifyField<uint32_t>(verifier, VT_SERVER_TICK_HZ, 4) &&
           VerifyOffset(verifier, VT_ASSIGNED_DISPATCH_AREAS) &&
           verifier.VerifyVector(assigned_dispatch_areas()) &&
           verifier.VerifyVectorOfTables(assigned_dispatch_areas()) &&
           VerifyField<uint64_t>(verifier, VT_SERVER_TIME_US, 8) &&
           verifier.EndTable();
  }
  HandshakeAckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HandshakeAckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<HandshakeAck> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HandshakeAckBuilder {
  typedef HandshakeAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_session_id(::flatbuffers::Offset<::flatbuffers::String> session_id) {
    fbb_.AddOffset(HandshakeAck::VT_SESSION_ID, session_id);
  }
  void add_server_tick_hz(uint32_t server_tick_hz) {
    fbb_.AddElement<uint32_t>(HandshakeAck::VT_SERVER_TICK_HZ, server_tick_hz, 20);
  }
  void add_assigned_dispatch_areas(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proto::DispatchAreaInfo>>> assigned_dispatch_areas) {
    fbb_.AddOffset(HandshakeAck::VT_ASSIGNED_DISPATCH_AREAS, assigned_dispatch_areas);
  }
  void add_server_time_us(uint64_t server_time_us) {
    fbb_.AddElement<uint64_t>(HandshakeAck::VT_SERVER_TIME_US, server_time_us, 0);
  }
  explicit HandshakeAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HandshakeAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HandshakeAck>(end);
    fbb_.Required(o, HandshakeAck::VT_SESSION_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<HandshakeAck> CreateHandshakeAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> session_id = 0,
    uint32_t server_tick_hz = 20,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proto::DispatchAreaInfo>>> assigned_dispatch_areas = 0,
    uint64_t server_time_us = 0) {
  HandshakeAckBuilder builder_(_fbb);
  builder_.add_server_time_us(server_time_us);
  builder_.add_assigned_dispatch_areas(assigned_dispatch_areas);
  builder_.add_server_tick_hz(server_tick_hz);
  builder_.add_session_id(session_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<HandshakeAck> CreateHandshakeAckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *session_id = nullptr,
    uint32_t server_tick_hz = 20,
    const std::vector<::flatbuffers::Offset<proto::DispatchAreaInfo>> *assigned_dispatch_areas = nullptr,
    uint64_t server_time_us = 0) {
  auto session_id__ = session_id ? _fbb.CreateString(session_id) : 0;
  auto assigned_dispatch_areas__ = assigned_dispatch_areas ? _fbb.CreateVector<::flatbuffers::Offset<proto::DispatchAreaInfo>>(*assigned_dispatch_areas) : 0;
  return proto::CreateHandshakeAck(
      _fbb,
      session_id__,
      server_tick_hz,
      assigned_dispatch_areas__,
      server_time_us);
}

::flatbuffers::Offset<HandshakeAck> CreateHandshakeAck(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HeartbeatT : public ::flatbuffers::NativeTable {
  typedef Heartbeat TableType;
  uint64_t sender_time_us = 0;
};

/// C ↔ S  (msg_type 0x03)
struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatT NativeTableType;
  typedef HeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SENDER_TIME_US = 4
  };
  /// Sender wall-clock time in microseconds (diagnostics/latency probe).
  uint64_t sender_time_us() const {
    return GetField<uint64_t>(VT_SENDER_TIME_US, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SENDER_TIME_US, 8) &&
           verifier.EndTable();
  }
  HeartbeatT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Heartbeat> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sender_time_us(uint64_t sender_time_us) {
    fbb_.AddElement<uint64_t>(Heartbeat::VT_SENDER_TIME_US, sender_time_us, 0);
  }
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t sender_time_us = 0) {
  HeartbeatBuilder builder_(_fbb);
  builder_.add_sender_time_us(sender_time_us);
  return builder_.Finish();
}

::flatbuffers::Offset<Heartbeat> CreateHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct HeartbeatAckT : public ::flatbuffers::NativeTable {
  typedef HeartbeatAck TableType;
  uint32_t req_seq_id = 0;
  uint64_t responder_time_us = 0;
};

/// C ↔ S  (msg_type 0x04)
struct HeartbeatAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatAckT NativeTableType;
  typedef HeartbeatAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_SEQ_ID = 4,
    VT_RESPONDER_TIME_US = 6
  };
  /// seq_id of HEARTBEAT frame being acknowledged.
  uint32_t req_seq_id() const {
    return GetField<uint32_t>(VT_REQ_SEQ_ID, 0);
  }
  /// Responder wall-clock time in microseconds.
  uint64_t responder_time_us() const {
    return GetField<uint64_t>(VT_RESPONDER_TIME_US, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_SEQ_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_RESPONDER_TIME_US, 8) &&
           verifier.EndTable();
  }
  HeartbeatAckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HeartbeatAckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<HeartbeatAck> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HeartbeatAckBuilder {
  typedef HeartbeatAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_seq_id(uint32_t req_seq_id) {
    fbb_.AddElement<uint32_t>(HeartbeatAck::VT_REQ_SEQ_ID, req_seq_id, 0);
  }
  void add_responder_time_us(uint64_t responder_time_us) {
    fbb_.AddElement<uint64_t>(HeartbeatAck::VT_RESPONDER_TIME_US, responder_time_us, 0);
  }
  explicit HeartbeatAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HeartbeatAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HeartbeatAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HeartbeatAck> CreateHeartbeatAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_seq_id = 0,
    uint64_t responder_time_us = 0) {
  HeartbeatAckBuilder builder_(_fbb);
  builder_.add_responder_time_us(responder_time_us);
  builder_.add_req_seq_id(req_seq_id);
  return builder_.Finish();
}

::flatbuffers::Offset<HeartbeatAck> CreateHeartbeatAck(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SnapshotRequestT : public ::flatbuffers::NativeTable {
  typedef SnapshotRequest TableType;
  uint32_t since_seq_id = 0;
  bool force_full = true;
};

/// C → S  (msg_type 0x30)
struct SnapshotRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnapshotRequestT NativeTableType;
  typedef SnapshotRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SINCE_SEQ_ID = 4,
    VT_FORCE_FULL = 6
  };
  /// Optional cursor for incremental catch-up; 0 means full snapshot.
  uint32_t since_seq_id() const {
    return GetField<uint32_t>(VT_SINCE_SEQ_ID, 0);
  }
  /// Force full snapshot even when server supports diff mode.
  bool force_full() const {
    return GetField<uint8_t>(VT_FORCE_FULL, 1) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SINCE_SEQ_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_FORCE_FULL, 1) &&
           verifier.EndTable();
  }
  SnapshotRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SnapshotRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SnapshotRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SnapshotRequestBuilder {
  typedef SnapshotRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_since_seq_id(uint32_t since_seq_id) {
    fbb_.AddElement<uint32_t>(SnapshotRequest::VT_SINCE_SEQ_ID, since_seq_id, 0);
  }
  void add_force_full(bool force_full) {
    fbb_.AddElement<uint8_t>(SnapshotRequest::VT_FORCE_FULL, static_cast<uint8_t>(force_full), 1);
  }
  explicit SnapshotRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SnapshotRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SnapshotRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SnapshotRequest> CreateSnapshotRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t since_seq_id = 0,
    bool force_full = true) {
  SnapshotRequestBuilder builder_(_fbb);
  builder_.add_since_seq_id(since_seq_id);
  builder_.add_force_full(force_full);
  return builder_.Finish();
}

::flatbuffers::Offset<SnapshotRequest> CreateSnapshotRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SessionNoticeT : public ::flatbuffers::NativeTable {
  typedef SessionNotice TableType;
  proto::SessionNoticeType type = proto::SessionNoticeType_INFO;
  uint16_t code = 0;
  std::string message{};
  std::string station_sid{};
  std::string dispatch_area_id{};
};

/// S → C  (msg_type 0x40)
struct SessionNotice FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SessionNoticeT NativeTableType;
  typedef SessionNoticeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_CODE = 6,
    VT_MESSAGE = 8,
    VT_STATION_SID = 10,
    VT_DISPATCH_AREA_ID = 12
  };
  proto::SessionNoticeType type() const {
    return static_cast<proto::SessionNoticeType>(GetField<int8_t>(VT_TYPE, 0));
  }
  /// Optional machine-readable code for client-side localization/UX.
  uint16_t code() const {
    return GetField<uint16_t>(VT_CODE, 0);
  }
  /// Human-readable fallback text.
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  /// Optional context IDs.
  const ::flatbuffers::String *station_sid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATION_SID);
  }
  const ::flatbuffers::String *dispatch_area_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DISPATCH_AREA_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint16_t>(verifier, VT_CODE, 2) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_STATION_SID) &&
           verifier.VerifyString(station_sid()) &&
           VerifyOffset(verifier, VT_DISPATCH_AREA_ID) &&
           verifier.VerifyString(dispatch_area_id()) &&
           verifier.EndTable();
  }
  SessionNoticeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SessionNoticeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<SessionNotice> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionNoticeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SessionNoticeBuilder {
  typedef SessionNotice Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(proto::SessionNoticeType type) {
    fbb_.AddElement<int8_t>(SessionNotice::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_code(uint16_t code) {
    fbb_.AddElement<uint16_t>(SessionNotice::VT_CODE, code, 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(SessionNotice::VT_MESSAGE, message);
  }
  void add_station_sid(::flatbuffers::Offset<::flatbuffers::String> station_sid) {
    fbb_.AddOffset(SessionNotice::VT_STATION_SID, station_sid);
  }
  void add_dispatch_area_id(::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id) {
    fbb_.AddOffset(SessionNotice::VT_DISPATCH_AREA_ID, dispatch_area_id);
  }
  explicit SessionNoticeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SessionNotice> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SessionNotice>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SessionNotice> CreateSessionNotice(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    proto::SessionNoticeType type = proto::SessionNoticeType_INFO,
    uint16_t code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> station_sid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> dispatch_area_id = 0) {
  SessionNoticeBuilder builder_(_fbb);
  builder_.add_dispatch_area_id(dispatch_area_id);
  builder_.add_station_sid(station_sid);
  builder_.add_message(message);
  builder_.add_code(code);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SessionNotice> CreateSessionNoticeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    proto::SessionNoticeType type = proto::SessionNoticeType_INFO,
    uint16_t code = 0,
    const char *message = nullptr,
    const char *station_sid = nullptr,
    const char *dispatch_area_id = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto station_sid__ = station_sid ? _fbb.CreateString(station_sid) : 0;
  auto dispatch_area_id__ = dispatch_area_id ? _fbb.CreateString(dispatch_area_id) : 0;
  return proto::CreateSessionNotice(
      _fbb,
      type,
      code,
      message__,
      station_sid__,
      dispatch_area_id__);
}

::flatbuffers::Offset<SessionNotice> CreateSessionNotice(::flatbuffers::FlatBufferBuilder &_fbb, const SessionNoticeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DispatchAreaInfoT *DispatchAreaInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DispatchAreaInfoT>(new DispatchAreaInfoT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DispatchAreaInfo::UnPackTo(DispatchAreaInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dispatch_area_id(); if (_e) _o->dispatch_area_id = _e->str(); }
  { auto _e = station_sid(); if (_e) _o->station_sid = _e->str(); }
  { auto _e = display_name(); if (_e) _o->display_name = _e->str(); }
}

inline ::flatbuffers::Offset<DispatchAreaInfo> CreateDispatchAreaInfo(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DispatchAreaInfo::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DispatchAreaInfo> DispatchAreaInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DispatchAreaInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DispatchAreaInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dispatch_area_id = _fbb.CreateString(_o->dispatch_area_id);
  auto _station_sid = _fbb.CreateString(_o->station_sid);
  auto _display_name = _o->display_name.empty() ? 0 : _fbb.CreateString(_o->display_name);
  return proto::CreateDispatchAreaInfo(
      _fbb,
      _dispatch_area_id,
      _station_sid,
      _display_name);
}

inline HandshakeT *Handshake::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HandshakeT>(new HandshakeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Handshake::UnPackTo(HandshakeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = proto_version(); _o->proto_version = _e; }
  { auto _e = player_id(); if (_e) _o->player_id = _e->str(); }
  { auto _e = auth_token(); if (_e) _o->auth_token = _e->str(); }
  { auto _e = client_version(); if (_e) _o->client_version = _e->str(); }
}

inline ::flatbuffers::Offset<Handshake> CreateHandshake(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Handshake::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Handshake> Handshake::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HandshakeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _proto_version = _o->proto_version;
  auto _player_id = _fbb.CreateString(_o->player_id);
  auto _auth_token = _fbb.CreateString(_o->auth_token);
  auto _client_version = _o->client_version.empty() ? 0 : _fbb.CreateString(_o->client_version);
  return proto::CreateHandshake(
      _fbb,
      _proto_version,
      _player_id,
      _auth_token,
      _client_version);
}

inline HandshakeAckT::HandshakeAckT(const HandshakeAckT &o)
      : session_id(o.session_id),
        server_tick_hz(o.server_tick_hz),
        server_time_us(o.server_time_us) {
  assigned_dispatch_areas.reserve(o.assigned_dispatch_areas.size());
  for (const auto &assigned_dispatch_areas_ : o.assigned_dispatch_areas) { assigned_dispatch_areas.emplace_back((assigned_dispatch_areas_) ? new proto::DispatchAreaInfoT(*assigned_dispatch_areas_) : nullptr); }
}

inline HandshakeAckT &HandshakeAckT::operator=(HandshakeAckT o) FLATBUFFERS_NOEXCEPT {
  std::swap(session_id, o.session_id);
  std::swap(server_tick_hz, o.server_tick_hz);
  std::swap(assigned_dispatch_areas, o.assigned_dispatch_areas);
  std::swap(server_time_us, o.server_time_us);
  return *this;
}

inline HandshakeAckT *HandshakeAck::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HandshakeAckT>(new HandshakeAckT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void HandshakeAck::UnPackTo(HandshakeAckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = session_id(); if (_e) _o->session_id = _e->str(); }
  { auto _e = server_tick_hz(); _o->server_tick_hz = _e; }
  { auto _e = assigned_dispatch_areas(); if (_e) { _o->assigned_dispatch_areas.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->assigned_dispatch_areas[_i]) { _e->Get(_i)->UnPackTo(_o->assigned_dispatch_areas[_i].get(), _resolver); } else { _o->assigned_dispatch_areas[_i] = std::unique_ptr<proto::DispatchAreaInfoT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->assigned_dispatch_areas.resize(0); } }
  { auto _e = server_time_us(); _o->server_time_us = _e; }
}

inline ::flatbuffers::Offset<HandshakeAck> CreateHandshakeAck(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return HandshakeAck::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<HandshakeAck> HandshakeAck::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HandshakeAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HandshakeAckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _session_id = _fbb.CreateString(_o->session_id);
  auto _server_tick_hz = _o->server_tick_hz;
  auto _assigned_dispatch_areas = _o->assigned_dispatch_areas.size() ? _fbb.CreateVector<::flatbuffers::Offset<proto::DispatchAreaInfo>> (_o->assigned_dispatch_areas.size(), [](size_t i, _VectorArgs *__va) { return CreateDispatchAreaInfo(*__va->__fbb, __va->__o->assigned_dispatch_areas[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _server_time_us = _o->server_time_us;
  return proto::CreateHandshakeAck(
      _fbb,
      _session_id,
      _server_tick_hz,
      _assigned_dispatch_areas,
      _server_time_us);
}

inline HeartbeatT *Heartbeat::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HeartbeatT>(new HeartbeatT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Heartbeat::UnPackTo(HeartbeatT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = sender_time_us(); _o->sender_time_us = _e; }
}

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Heartbeat::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Heartbeat> Heartbeat::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HeartbeatT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _sender_time_us = _o->sender_time_us;
  return proto::CreateHeartbeat(
      _fbb,
      _sender_time_us);
}

inline HeartbeatAckT *HeartbeatAck::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<HeartbeatAckT>(new HeartbeatAckT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void HeartbeatAck::UnPackTo(HeartbeatAckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = req_seq_id(); _o->req_seq_id = _e; }
  { auto _e = responder_time_us(); _o->responder_time_us = _e; }
}

inline ::flatbuffers::Offset<HeartbeatAck> CreateHeartbeatAck(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return HeartbeatAck::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<HeartbeatAck> HeartbeatAck::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const HeartbeatAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const HeartbeatAckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _req_seq_id = _o->req_seq_id;
  auto _responder_time_us = _o->responder_time_us;
  return proto::CreateHeartbeatAck(
      _fbb,
      _req_seq_id,
      _responder_time_us);
}

inline SnapshotRequestT *SnapshotRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SnapshotRequestT>(new SnapshotRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SnapshotRequest::UnPackTo(SnapshotRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = since_seq_id(); _o->since_seq_id = _e; }
  { auto _e = force_full(); _o->force_full = _e; }
}

inline ::flatbuffers::Offset<SnapshotRequest> CreateSnapshotRequest(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SnapshotRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SnapshotRequest> SnapshotRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SnapshotRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SnapshotRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _since_seq_id = _o->since_seq_id;
  auto _force_full = _o->force_full;
  return proto::CreateSnapshotRequest(
      _fbb,
      _since_seq_id,
      _force_full);
}

inline SessionNoticeT *SessionNotice::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<SessionNoticeT>(new SessionNoticeT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void SessionNotice::UnPackTo(SessionNoticeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = code(); _o->code = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
  { auto _e = station_sid(); if (_e) _o->station_sid = _e->str(); }
  { auto _e = dispatch_area_id(); if (_e) _o->dispatch_area_id = _e->str(); }
}

inline ::flatbuffers::Offset<SessionNotice> CreateSessionNotice(::flatbuffers::FlatBufferBuilder &_fbb, const SessionNoticeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return SessionNotice::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<SessionNotice> SessionNotice::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SessionNoticeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SessionNoticeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _code = _o->code;
  auto _message = _o->message.empty() ? 0 : _fbb.CreateString(_o->message);
  auto _station_sid = _o->station_sid.empty() ? 0 : _fbb.CreateString(_o->station_sid);
  auto _dispatch_area_id = _o->dispatch_area_id.empty() ? 0 : _fbb.CreateString(_o->dispatch_area_id);
  return proto::CreateSessionNotice(
      _fbb,
      _type,
      _code,
      _message,
      _station_sid,
      _dispatch_area_id);
}

inline const proto::HandshakeAck *GetHandshakeAck(const void *buf) {
  return ::flatbuffers::GetRoot<proto::HandshakeAck>(buf);
}

inline const proto::HandshakeAck *GetSizePrefixedHandshakeAck(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proto::HandshakeAck>(buf);
}

template <bool B = false>
inline bool VerifyHandshakeAckBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<proto::HandshakeAck>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedHandshakeAckBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<proto::HandshakeAck>(nullptr);
}

inline void FinishHandshakeAckBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::HandshakeAck> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedHandshakeAckBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::HandshakeAck> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::HandshakeAckT> UnPackHandshakeAck(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::HandshakeAckT>(GetHandshakeAck(buf)->UnPack(res));
}

inline std::unique_ptr<proto::HandshakeAckT> UnPackSizePrefixedHandshakeAck(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::HandshakeAckT>(GetSizePrefixedHandshakeAck(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_SESSION_PROTO_H_
