// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VOICE_PROTO_H_
#define FLATBUFFERS_GENERATED_VOICE_PROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace proto {

struct VoiceChanJoin;
struct VoiceChanJoinBuilder;
struct VoiceChanJoinT;

struct VoiceChanLeave;
struct VoiceChanLeaveBuilder;
struct VoiceChanLeaveT;

struct VoiceParticipant;
struct VoiceParticipantBuilder;
struct VoiceParticipantT;

struct VoiceChanState;
struct VoiceChanStateBuilder;
struct VoiceChanStateT;

struct VoiceChanJoinT : public ::flatbuffers::NativeTable {
  typedef VoiceChanJoin TableType;
  std::string channel_id{};
};

/// C → S  (msg_type 0x70)
struct VoiceChanJoin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VoiceChanJoinT NativeTableType;
  typedef VoiceChanJoinBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL_ID = 4
  };
  const ::flatbuffers::String *channel_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHANNEL_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CHANNEL_ID) &&
           verifier.VerifyString(channel_id()) &&
           verifier.EndTable();
  }
  VoiceChanJoinT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoiceChanJoinT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<VoiceChanJoin> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanJoinT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoiceChanJoinBuilder {
  typedef VoiceChanJoin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel_id(::flatbuffers::Offset<::flatbuffers::String> channel_id) {
    fbb_.AddOffset(VoiceChanJoin::VT_CHANNEL_ID, channel_id);
  }
  explicit VoiceChanJoinBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VoiceChanJoin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VoiceChanJoin>(end);
    fbb_.Required(o, VoiceChanJoin::VT_CHANNEL_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<VoiceChanJoin> CreateVoiceChanJoin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> channel_id = 0) {
  VoiceChanJoinBuilder builder_(_fbb);
  builder_.add_channel_id(channel_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VoiceChanJoin> CreateVoiceChanJoinDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *channel_id = nullptr) {
  auto channel_id__ = channel_id ? _fbb.CreateString(channel_id) : 0;
  return proto::CreateVoiceChanJoin(
      _fbb,
      channel_id__);
}

::flatbuffers::Offset<VoiceChanJoin> CreateVoiceChanJoin(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanJoinT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct VoiceChanLeaveT : public ::flatbuffers::NativeTable {
  typedef VoiceChanLeave TableType;
  std::string channel_id{};
};

/// C → S  (msg_type 0x71)
struct VoiceChanLeave FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VoiceChanLeaveT NativeTableType;
  typedef VoiceChanLeaveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL_ID = 4
  };
  const ::flatbuffers::String *channel_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHANNEL_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CHANNEL_ID) &&
           verifier.VerifyString(channel_id()) &&
           verifier.EndTable();
  }
  VoiceChanLeaveT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoiceChanLeaveT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<VoiceChanLeave> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanLeaveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoiceChanLeaveBuilder {
  typedef VoiceChanLeave Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel_id(::flatbuffers::Offset<::flatbuffers::String> channel_id) {
    fbb_.AddOffset(VoiceChanLeave::VT_CHANNEL_ID, channel_id);
  }
  explicit VoiceChanLeaveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VoiceChanLeave> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VoiceChanLeave>(end);
    fbb_.Required(o, VoiceChanLeave::VT_CHANNEL_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<VoiceChanLeave> CreateVoiceChanLeave(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> channel_id = 0) {
  VoiceChanLeaveBuilder builder_(_fbb);
  builder_.add_channel_id(channel_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VoiceChanLeave> CreateVoiceChanLeaveDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *channel_id = nullptr) {
  auto channel_id__ = channel_id ? _fbb.CreateString(channel_id) : 0;
  return proto::CreateVoiceChanLeave(
      _fbb,
      channel_id__);
}

::flatbuffers::Offset<VoiceChanLeave> CreateVoiceChanLeave(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanLeaveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct VoiceParticipantT : public ::flatbuffers::NativeTable {
  typedef VoiceParticipant TableType;
  std::string client_id{};
  bool muted = false;
  bool deafened = false;
};

struct VoiceParticipant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VoiceParticipantT NativeTableType;
  typedef VoiceParticipantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_MUTED = 6,
    VT_DEAFENED = 8
  };
  const ::flatbuffers::String *client_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CLIENT_ID);
  }
  bool muted() const {
    return GetField<uint8_t>(VT_MUTED, 0) != 0;
  }
  bool deafened() const {
    return GetField<uint8_t>(VT_DEAFENED, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CLIENT_ID) &&
           verifier.VerifyString(client_id()) &&
           VerifyField<uint8_t>(verifier, VT_MUTED, 1) &&
           VerifyField<uint8_t>(verifier, VT_DEAFENED, 1) &&
           verifier.EndTable();
  }
  VoiceParticipantT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoiceParticipantT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<VoiceParticipant> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceParticipantT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoiceParticipantBuilder {
  typedef VoiceParticipant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(::flatbuffers::Offset<::flatbuffers::String> client_id) {
    fbb_.AddOffset(VoiceParticipant::VT_CLIENT_ID, client_id);
  }
  void add_muted(bool muted) {
    fbb_.AddElement<uint8_t>(VoiceParticipant::VT_MUTED, static_cast<uint8_t>(muted), 0);
  }
  void add_deafened(bool deafened) {
    fbb_.AddElement<uint8_t>(VoiceParticipant::VT_DEAFENED, static_cast<uint8_t>(deafened), 0);
  }
  explicit VoiceParticipantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VoiceParticipant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VoiceParticipant>(end);
    fbb_.Required(o, VoiceParticipant::VT_CLIENT_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<VoiceParticipant> CreateVoiceParticipant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> client_id = 0,
    bool muted = false,
    bool deafened = false) {
  VoiceParticipantBuilder builder_(_fbb);
  builder_.add_client_id(client_id);
  builder_.add_deafened(deafened);
  builder_.add_muted(muted);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VoiceParticipant> CreateVoiceParticipantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *client_id = nullptr,
    bool muted = false,
    bool deafened = false) {
  auto client_id__ = client_id ? _fbb.CreateString(client_id) : 0;
  return proto::CreateVoiceParticipant(
      _fbb,
      client_id__,
      muted,
      deafened);
}

::flatbuffers::Offset<VoiceParticipant> CreateVoiceParticipant(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceParticipantT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct VoiceChanStateT : public ::flatbuffers::NativeTable {
  typedef VoiceChanState TableType;
  std::string channel_id{};
  std::vector<std::unique_ptr<proto::VoiceParticipantT>> participants{};
  VoiceChanStateT() = default;
  VoiceChanStateT(const VoiceChanStateT &o);
  VoiceChanStateT(VoiceChanStateT&&) FLATBUFFERS_NOEXCEPT = default;
  VoiceChanStateT &operator=(VoiceChanStateT o) FLATBUFFERS_NOEXCEPT;
};

/// S → C  (msg_type 0x72)
struct VoiceChanState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VoiceChanStateT NativeTableType;
  typedef VoiceChanStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHANNEL_ID = 4,
    VT_PARTICIPANTS = 6
  };
  const ::flatbuffers::String *channel_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHANNEL_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<proto::VoiceParticipant>> *participants() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<proto::VoiceParticipant>> *>(VT_PARTICIPANTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CHANNEL_ID) &&
           verifier.VerifyString(channel_id()) &&
           VerifyOffset(verifier, VT_PARTICIPANTS) &&
           verifier.VerifyVector(participants()) &&
           verifier.VerifyVectorOfTables(participants()) &&
           verifier.EndTable();
  }
  VoiceChanStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoiceChanStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<VoiceChanState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoiceChanStateBuilder {
  typedef VoiceChanState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_channel_id(::flatbuffers::Offset<::flatbuffers::String> channel_id) {
    fbb_.AddOffset(VoiceChanState::VT_CHANNEL_ID, channel_id);
  }
  void add_participants(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proto::VoiceParticipant>>> participants) {
    fbb_.AddOffset(VoiceChanState::VT_PARTICIPANTS, participants);
  }
  explicit VoiceChanStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VoiceChanState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VoiceChanState>(end);
    fbb_.Required(o, VoiceChanState::VT_CHANNEL_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<VoiceChanState> CreateVoiceChanState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> channel_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proto::VoiceParticipant>>> participants = 0) {
  VoiceChanStateBuilder builder_(_fbb);
  builder_.add_participants(participants);
  builder_.add_channel_id(channel_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VoiceChanState> CreateVoiceChanStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *channel_id = nullptr,
    const std::vector<::flatbuffers::Offset<proto::VoiceParticipant>> *participants = nullptr) {
  auto channel_id__ = channel_id ? _fbb.CreateString(channel_id) : 0;
  auto participants__ = participants ? _fbb.CreateVector<::flatbuffers::Offset<proto::VoiceParticipant>>(*participants) : 0;
  return proto::CreateVoiceChanState(
      _fbb,
      channel_id__,
      participants__);
}

::flatbuffers::Offset<VoiceChanState> CreateVoiceChanState(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline VoiceChanJoinT *VoiceChanJoin::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<VoiceChanJoinT>(new VoiceChanJoinT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoiceChanJoin::UnPackTo(VoiceChanJoinT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = channel_id(); if (_e) _o->channel_id = _e->str(); }
}

inline ::flatbuffers::Offset<VoiceChanJoin> CreateVoiceChanJoin(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanJoinT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return VoiceChanJoin::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<VoiceChanJoin> VoiceChanJoin::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanJoinT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const VoiceChanJoinT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _channel_id = _fbb.CreateString(_o->channel_id);
  return proto::CreateVoiceChanJoin(
      _fbb,
      _channel_id);
}

inline VoiceChanLeaveT *VoiceChanLeave::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<VoiceChanLeaveT>(new VoiceChanLeaveT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoiceChanLeave::UnPackTo(VoiceChanLeaveT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = channel_id(); if (_e) _o->channel_id = _e->str(); }
}

inline ::flatbuffers::Offset<VoiceChanLeave> CreateVoiceChanLeave(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanLeaveT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return VoiceChanLeave::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<VoiceChanLeave> VoiceChanLeave::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanLeaveT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const VoiceChanLeaveT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _channel_id = _fbb.CreateString(_o->channel_id);
  return proto::CreateVoiceChanLeave(
      _fbb,
      _channel_id);
}

inline VoiceParticipantT *VoiceParticipant::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<VoiceParticipantT>(new VoiceParticipantT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoiceParticipant::UnPackTo(VoiceParticipantT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = client_id(); if (_e) _o->client_id = _e->str(); }
  { auto _e = muted(); _o->muted = _e; }
  { auto _e = deafened(); _o->deafened = _e; }
}

inline ::flatbuffers::Offset<VoiceParticipant> CreateVoiceParticipant(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceParticipantT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return VoiceParticipant::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<VoiceParticipant> VoiceParticipant::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceParticipantT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const VoiceParticipantT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _client_id = _fbb.CreateString(_o->client_id);
  auto _muted = _o->muted;
  auto _deafened = _o->deafened;
  return proto::CreateVoiceParticipant(
      _fbb,
      _client_id,
      _muted,
      _deafened);
}

inline VoiceChanStateT::VoiceChanStateT(const VoiceChanStateT &o)
      : channel_id(o.channel_id) {
  participants.reserve(o.participants.size());
  for (const auto &participants_ : o.participants) { participants.emplace_back((participants_) ? new proto::VoiceParticipantT(*participants_) : nullptr); }
}

inline VoiceChanStateT &VoiceChanStateT::operator=(VoiceChanStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(channel_id, o.channel_id);
  std::swap(participants, o.participants);
  return *this;
}

inline VoiceChanStateT *VoiceChanState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<VoiceChanStateT>(new VoiceChanStateT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoiceChanState::UnPackTo(VoiceChanStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = channel_id(); if (_e) _o->channel_id = _e->str(); }
  { auto _e = participants(); if (_e) { _o->participants.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->participants[_i]) { _e->Get(_i)->UnPackTo(_o->participants[_i].get(), _resolver); } else { _o->participants[_i] = std::unique_ptr<proto::VoiceParticipantT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->participants.resize(0); } }
}

inline ::flatbuffers::Offset<VoiceChanState> CreateVoiceChanState(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return VoiceChanState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<VoiceChanState> VoiceChanState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const VoiceChanStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const VoiceChanStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _channel_id = _fbb.CreateString(_o->channel_id);
  auto _participants = _o->participants.size() ? _fbb.CreateVector<::flatbuffers::Offset<proto::VoiceParticipant>> (_o->participants.size(), [](size_t i, _VectorArgs *__va) { return CreateVoiceParticipant(*__va->__fbb, __va->__o->participants[i].get(), __va->__rehasher); }, &_va ) : 0;
  return proto::CreateVoiceChanState(
      _fbb,
      _channel_id,
      _participants);
}

inline const proto::VoiceChanState *GetVoiceChanState(const void *buf) {
  return ::flatbuffers::GetRoot<proto::VoiceChanState>(buf);
}

inline const proto::VoiceChanState *GetSizePrefixedVoiceChanState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proto::VoiceChanState>(buf);
}

template <bool B = false>
inline bool VerifyVoiceChanStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<proto::VoiceChanState>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedVoiceChanStateBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<proto::VoiceChanState>(nullptr);
}

inline void FinishVoiceChanStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::VoiceChanState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVoiceChanStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proto::VoiceChanState> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<proto::VoiceChanStateT> UnPackVoiceChanState(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::VoiceChanStateT>(GetVoiceChanState(buf)->UnPack(res));
}

inline std::unique_ptr<proto::VoiceChanStateT> UnPackSizePrefixedVoiceChanState(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<proto::VoiceChanStateT>(GetSizePrefixedVoiceChanState(buf)->UnPack(res));
}

}  // namespace proto

#endif  // FLATBUFFERS_GENERATED_VOICE_PROTO_H_
